#!/bin/bash

topDirectory="$(dirname "${0}")/.."
make --silent -C "${topDirectory}" clone
. "${topDirectory}/prologue.sh"

checkDirectories() {
   local isClean=true
   local directory

   for directory in etc Files
   do
      verifyInputDirectory "${directory}"

      local output="$(git status --short "${directory}")"
      [ -n "${output}" ] || continue

      isClean=false
      logWarning "dirty directory: ${directory}"
      local line

      while read -r line
      do
         logTask "${line}"
      done <<<"${output}"
   done

   "${isClean}" || "${ignoreProblems}" || semanticError
}

makeTarget() {
   local target="${1}"

   logTask "making target: ${target}"
   executeHostCommand make --silent -- "${target}"
}

addTestModeOption
addProgramOption f flag ignoreProblems "force - proceed even if problems are detected"
addProgramOption A flag allActions "perform all of the actions"
addProgramOption u flag makeUnconfigure "unconfigure BRLTTY"
addProgramOption c flag makeConfigure "configure BRLTTY"
addProgramOption b flag makeBuild "build BRLTTY"
addProgramOption i flag makeInstall "install BRLTTY"
addProgramOption s flag makeSymlinks "make the symbolic links"
addProgramOption a flag makeArchives "make the archives"
parseProgramArguments "${@}"
verifyActionFlags allActions makeUnconfigure makeConfigure makeBuild makeInstall makeSymlinks makeArchives

set -e
cd "${topDirectory}"
checkDirectories

! "${makeUnconfigure}" || makeTarget unconfigure
! "${makeConfigure}" || makeTarget configure
! "${makeBuild}" || makeTarget build
! "${makeInstall}" || makeTarget install
! "${makeSymlinks}" || makeTarget symlinks

! "${makeArchives}" || {
   executeHostCommand rm -f -- *.tar
   makeTarget gzip-archive
   makeTarget bzip2-archive
   makeTarget xz-archive
}

exit 0
