#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2018 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.com/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

defaultIconSize="32x32"

. "`dirname "${0}"`/../../prologue.sh"
addProgramOption s string.geometry iconSize "the size (widthxheight) of the icon" "${defaultIconSize}"
addProgramParameter icon-file iconFile "the path (relative or absolute) to the icon file"
parseProgramArguments "${@}"

[ -n "${iconSize}" ] || iconSize="${defaultIconSize}"

label='⠃⠗⠇
⠞⠞⠽'

convert \
  -size "${iconSize}" \
  -gravity center \
  -channel RGBA \
  -background transparent \
  -fill white \
  -font assets/UBraille.ttf \
  label:"${label}" \
  "${iconFile}"

exit 0
