#!/bin/bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2021 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

set -e
umask 022

. "$(dirname "${0}")/../../brltty-prologue.sh"
addProgramParameter "source" sourceDirectory "the directory containing the tables"
addProgramParameter "target" targetDirectory "the directory into which to copy the tables"
parseProgramArguments "${@}"

while read file
do
   file="${file#${sourceDirectory}/}"
   source="$(dirname "${file}")"
   target="${targetDirectory}/${source}"

    mkdir -p -- "${target}"
   cp -p -- "${sourceDirectory}/${file}" "${target}/"
done < <(find "${sourceDirectory}" -type f -name '?*.?*' -print)

exit 0
