#!/bin/bash -p
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2019 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

set -e
umask 022

verifyDirectory() {
   local path="${1}"

   [ -e "${path}" ] || semanticError "directory not found: ${path}"
   [ -d "${path}" ] || semanticError "not a directory: ${path}"
   [ -w "${path}" ] || semanticError "directory not writable: ${path}"
   [ -r "${path}" ] || semanticError "directory not readable: ${path}"
   [ -x "${path}" ] || semanticError "directory not searchable: ${path}"
}

executeCommand() {
   logMessage detail "executing command: ${*}"

   exitStatus=0
   "${@}" || exitStatus="${?}"

   [ "${exitStatus}" -eq 0 ] || logMessage warning "command failed: ${1}: exit status ${exitStatus}"
   return "${exitStatus}"
}

unpackArchive() {
   local path="${1}"

   case "${path}"
   in
      *.zip) set -- unzip -q;;
      *.tar.gz) set -- tar xfz;;
      *) semanticError "unsupported archive: ${path}";;
   esac

   executeCommand "${@}" "${path}"
}

downloadFile() {
   local source="${1}"
   local target="${2}"

   logMessage step "downloading file: ${source}"
   [ -z "${target}" ] && target="${source##*/}"
   executeCommand wget -q -O "${target}" "${urlArchiveRoot}/${source}"
}

havePath() {
   local path="${1}"

   [ -n "${path}" ] || return 1
   [ -e "${path}" ] || return 2
   return 0
}

installWindowsArchive() {
   local archive="${1}"
   local path="${2}"

   havePath "${path}" || {
      logMessage task "installing Windows archive: ${archive}"
      downloadFile "${archive}"

      local directory=archive
      executeCommand mkdir "${directory}"
      executeCommand cd "${directory}"

      unpackArchive "../${archive}"
      set -- *

      if [ "${#}" -eq 1 -a -d "${1}" ]
      then
         executeCommand mv "${1}" "${path}"
         executeCommand cd ..
         executeCommand rmdir "${directory}"
      else
         executeCommand cd ..
         executeCommand mv "${directory}" "${path}"
      fi
   }
}

installMingwArchive() {
   local archive="${1}"
   local path="${2}"

   havePath "${mingwDirectory}/${path}" || {
      logMessage task "installing MinGW archive: ${archive}"
      downloadFile "MinGW/${archive}"

      executeCommand cd "${mingwDirectory}"
      unpackArchive "${temporaryDirectory}/${archive}"
      executeCommand cd "${temporaryDirectory}"
   }
}

installMingwPackage() {
   local package="${1}"
   local path="${2}"

   havePath "${path}" || {
      logMessage task "installing MinGW package: ${package}"
      executeCommand mingw-get install "${package}"
   }
}

installMingwHeader() {
   local header="${1}"

   local source="${header##*/}"
   local target="${headersDirectory}/${source}"

   [ -e "${target}" ] || {
      logMessage task "installing MinGW header: ${source}"
      downloadFile "${header}"
      executeCommand cp "${source}" "${target}"
   }
}

installMingwBinary() {
   local binary="${1}"

   local source="${binary##*/}"
   local binaryDirectory="${mingwDirectory}/local/bin" #restore should be /usr
   local target="${binaryDirectory}/${source}"

   [ -e "${target}" ] || {
      logMessage task "installing MinGW binary: ${source}"
      downloadFile "${binary}"
      [ -d "${binaryDirectory}" ] || executeCommand mkdir -p "${binaryDirectory}"
      executeCommand cp "${source}" "${target}"
   }
}

installRequiredPackages() {
   installMingwPackage msys-wget /usr/bin/wget
   installMingwPackage msys-unzip /usr/bin/unzip
}

installMsvcCommands() {
   local binary

   for binary in lib.exe link.exe mspdb100.dll msvcr100.dll
   do
      installMingwBinary "MSVC/${binary}"
   done
}

installBluetoothHeaders() {
   local name

   for name in ws2bth bthdef bthsdpdef
   do
      installMingwHeader "Bluetooth/${name}.h"
   done
}

. "`dirname "${0}"`/../prologue.sh"
#. "${programDirectory}/mingw.sh" #restore uncomment

urlArchiveRoot="http://brltty.app/archive/Windows"
windowsDirectory="/tmp/w" #restore should be /c
mingwDirectory="/tmp/m" #restore should be /mingw

headersDirectory="${mingwDirectory}/include"

defaultTemporaryDirectory="${TMPDIR:-/tmp}/brltty-${programName}"

addProgramOption k flag keepFiles "keep (do not remove) the temporary directory"
addProgramOption t string.directory temporaryDirectory "the temporary directory to use" "${defaultTemporaryDirectory}"
parseProgramArguments "${@}"

verifyDirectory "${windowsDirectory}"
verifyDirectory "${mingwDirectory}"
verifyDirectory "${headersDirectory}"

if [ -z "${temporaryDirectory}" ]
then
   temporaryDirectory="${defaultTemporaryDirectory}"
   rm -f -r "${temporaryDirectory}"
elif [ -e "${temporaryDirectory}" ]
then
   semanticError "directory already exists: ${temporaryDirectory}"
fi

mkdir -p "${temporaryDirectory}"
cd "${temporaryDirectory}"
temporaryDirectory="$(pwd -P)" #restore -P should be -W

installRequiredPackages
installMsvcCommands
installBluetoothHeaders

installMingwArchive pkg-config_0.28-1_win32.zip "bin/pkg-config.exe"
installMingwArchive glib_2.34.3-1_win32.zip "bin/libgobject-2.0-0.dll"

installWindowsArchive icu4c-53_1-Win32-msvc10.zip "${windowsDirectory}/ICU"
installWindowsArchive libusb-win32-bin-1.2.6.0.zip "${windowsDirectory}/LibUSB-Win32"
installWindowsArchive libusbx-1.0.18-win.tar.gz "${windowsDirectory}/LibUSB-1.0"
installWindowsArchive winusb.zip "${windowsDirectory}/WinUSB"

"${keepFiles}" || {
   logMessage task "cleaning up"
   cd "${initialDirectory}"
   rm -f -r "${temporaryDirectory}"
}

logMessage task "done"
exit 0
