#!/bin/bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2025 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/../brltty-prologue.sh"
. "${programDirectory}/mingw64.sh"

set -e
umask 022

readonly toolsDirectory="${programDirectory}/../Tools"

readonly packageList=(
   mingw64/mingw-w64-x86_64-libiconv
   mingw64/mingw-w64-x86_64-libsystre
   mingw64/mingw-w64-x86_64-libusb
   mingw64/mingw-w64-x86_64-libusb-win32
   mingw64/mingw-w64-x86_64-ncurses

   msys/autoconf-wrapper
   msys/binutils
   msys/tcl
   msys/git

   msys/make
   mingw64/mingw-w64-x86_64-gcc
   mingw64/mingw-w64-x86_64-clang

   msys/tar
   msys/gzip
   msys/bzip2
   msys/xz
   msys/zip
   msys/unzip

   msys/gettext
   msys/doxygen
)

"${toolsDirectory}/pkg-install" "${packageList[@]}"
exit 0
