#!/bin/bash

. "$(dirname "${0}")/prologue.sh"
addSourceTreeOption
addBuildTreeOption
parseProgramArguments "${@}"

verifySourceTree
verifyBuildTree

set -e
getInstallTree installTree

for subdirectory in bin libexec
do
   sudo cp -- "${programDirectory}/${subdirectory}/"* "${installTree}/${subdirectory}/"
done

for subdirectory in etc
do
   sudo tar --create --file "${installTree}/${subdirectory}.tar" "${subdirectory}"
done

exit 0
