#!/bin/bash

. "$(dirname "${0}")/prologue.sh"
addSourceTreeOption
addBuildTreeOption
parseProgramArguments "${@}"

verifySourceTree
verifyBuildTree

set -e
getInstallTree installTree

for sourceDirectory in Files/*
do
   targetDirectory="${installTree}/${sourceDirectory#*/}"
   sudo cp -- "${programDirectory}/${sourceDirectory}/"* "${targetDirectory}/"
done

for subdirectory in etc
do
   sudo tar --create --file "${installTree}/${subdirectory}.tar" "${subdirectory}"
done

exit 0
