###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2025 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

os: Visual Studio 2022
version: "appveyor-{build}"
branches:
  only:
    - master

environment:
  PY_PYTHON: 3.11-32

init:
  - ps: |
      If (([regex]::Matches($env:APPVEYOR_BUILD_VERSION, "," )).count -eq 0) {
       If ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        Update-AppveyorBuild -Version ("pr$env:APPVEYOR_PULL_REQUEST_NUMBER-$env:APPVEYOR_BUILD_NUMBER-" + $env:APPVEYOR_REPO_COMMIT.Substring(0, 8))
       } Else {
        Update-AppveyorBuild -Version ("$env:APPVEYOR_BUILD_VERSION-" + $env:APPVEYOR_REPO_COMMIT.Substring(0, 8))
       }
      }

clone_depth: 1

install:
  - echo %APPVEYOR_BUILD_VERSION% > %APPVEYOR_BUILD_FOLDER%\REVISION
  # Hack, getrevid doesn't seem to work in forks of the brltty repository.
  # Removing .git ensures the REVISION is used.
  - rmdir /Q /S .git
  - cmd: |
      C:\MinGW\msys\1.0\bin\bash.exe -lc "cd $APPVEYOR_BUILD_FOLDER; windows/winsetup"

build_script:
  - cmd: |
      C:\MinGW\msys\1.0\bin\bash.exe -lc "cd $APPVEYOR_BUILD_FOLDER; ./autogen; Windows/mkwin ./ $APPVEYOR_BUILD_VERSION"

artifacts:
  - path: "*.zip"
  - path: "*.exe"
