#!/usr/bin/env bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2025 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

readonly programArguments=("${@}")
. "$(dirname "${0}")/brltty-prologue.sh"

showProgramUsagePurpose() {
cat <<END_OF_PROGRAM_USAGE_PURPOSE
Run a brltty instance that monitors the current tmux session and uses BrlAPI to communicate with the main brltty instance.
END_OF_PROGRAM_USAGE_PURPOSE
}

showProgramUsageNotes() {
cat <<END_OF_PROGRAM_USAGE_NOTES
Any command line arguments specified after -- are treated as brltty options.
END_OF_PROGRAM_USAGE_NOTES
}

processExtraProgramParameters() {
   readonly programParameters=("${@}")
}

optionalProgramParameters "argument" "additional options passed through to brltty"
parseProgramArguments "${@}"

brailleDriver=ba # BrlAPI
screenDriver=tx # Tmux

tmuxSocket="${TMUX}"
[ -n "${tmuxSocket}" ] || semanticError "not using tmux"

brlttyOptions=(
  "--braille-driver=${brailleDriver}"
  "--screen-driver=${screenDriver}"
  "--screen-parameters=${screenDriver}:socket=${tmuxSocket}"
)

[ "$(id -u)" -eq 0 ] || {
   exec sudo --preserve-env=TMUX -- "${programDirectory}/${programName}" "${programArguments[@]}"
   exit "${?}"
}

export CONTROLVT="$(fgconsole)"

findSiblingCommand brlttyPath brltty run-brltty || semanticError "brltty not found"
"${brlttyPath}" "${brlttyOptions[@]}" "${programParameters[@]}"
exit 0
