#!/usr/bin/env bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2022 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "$(dirname "${0}")/brltty-prologue.sh"

[ -t 0 ] || semanticError "standard input isn't a terminal"
[ -t 1 ] || semanticError "standard output isn't a terminal"

findSiblingCommand brlttyPath brltty run-brltty || {
   semanticError "brltty not found"
}

command="${BRLTTY_TERM_COMMAND:-${SHELL:-/bin/sh}}"
findHostCommand commandPath "${command}" || {
   semanticError "command not found: ${command}"
}

addDriverParameter() {
   local name="${1}"
   local value="${2}"

  driverParameters+=("-Xem:${name}=${value}")
}

driverParameters=()
addDriverParameter command "${commandPath}"
addDriverParameter user "$(id -u)"
addDriverParameter group "$(id -g)"
addDriverParameter directory "${PWD}"
addDriverParameter home "${HOME}"

SUDO=""
[ -u "${brlttyPath}" ] || SUDO="sudo"

exec ${SUDO} "${brlttyPath}" -n -z -xem "${driverParameters[@]}" "${@}"
exit "${?}"
