#!/bin/bash
set -e

atspiDirectory="/usr/lib/at-spi2-core"
eval $(dbus-launch --sh-syntax --exit-with-session)
export GTK_MODULES=gail:atk-bridge

"${atspiDirectory}/at-spi-bus-launcher" &
"${atspiDirectory}/at-spi2-registryd" &

export BRLAPI_HOST=":canute"
brlttyPath="/brltty/current/bin"
"${brlttyPath}/xbrlapi"
"${brlttyPath}/brltty" -N -f /etc/brltty-atspi.conf

exec gnome-terminal --geometry 40x9
exit "${?}"
