#!/bin/bash -p
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2018 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.com/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

./configure \
   --disable-gpm \
   --disable-iconv \
   --disable-polkit \
   \
   --without-libbraille \
   \
   --without-espeak \
   --without-flite \
   --without-mikropuhe \
   --without-speechd \
   --without-swift \
   --without-theta \
   --without-viavoice \
   \
   --without-pgmpath-package \
   --without-service-package \
   --without-params-package \
   --without-charset-package \
   --without-mntpt-package \
   --without-mntfs-package \
   --without-kbd-package \
   --without-bell-package \
   --without-leds-package \
   --without-beep-package \
   --without-pcm-package \
   --without-fm-package \
   --without-ports-package \
   \
   --disable-java-bindings \
   --disable-ocaml-bindings \
   --disable-python-bindings \
   --disable-tcl-bindings \
   \
   --quiet \
   "${@}"
exit "${?}"
