#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2014 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any
# later version. Please see the file LICENSE-GPL for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"
set -e
export CC="gcc -m32"

"${programDirectory}/configure" \
   --enable-standalone-programs \
   --disable-api \
   --disable-gpm \
   --disable-icu \
   --disable-x \
   --disable-contracted-braille \
   --with-braille-driver=ir,-all \
   --disable-speech-support \
   --with-screen-driver=lx,-all \
   --without-usb-package \
   --without-bluetooth-package \
   --without-pcm-package \
   --without-midi-package \
   --quiet "${@}"

exit 0
