#!/bin/bash -p
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2023 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/brltty-prologue.bash"

handleInitialHelpOption "${@}" <<END-OF-HELP
Configure a BRLTTY build for the Windows platform.

Syntax: ${programName} {-h | [-option ...]}

All of the options are passed through, unmodified, as additional options to the configure script.
END-OF-HELP

configureOptions=(
   --enable-relocatable-install

   --disable-expat
   --disable-gpm
   --disable-i18n
   --disable-icu
   --disable-liblouis
   --disable-polkit
   --disable-x

   --without-libbraille
   --disable-speech-support

   --without-pgmprivs-package
   --without-params-package
   --without-rgx-package
   --without-mntpt-package
   --without-mntfs-package
   --without-kbd-package
   --without-bell-package
   --without-leds-package
   --without-hid-package

   --disable-emacs-bindings
   --disable-java-bindings
   --disable-lua-bindings
   --disable-ocaml-bindings
   --disable-tcl-bindings
)

toRelativePath "${programDirectory}" configureDirectory
"${configureDirectory}/configure" --quiet "${configureOptions[@]}" "${@}"
exit "${?}"
