#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2018 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.com/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

# Braille drivers already disabled:
# ba (by --disable-api)
# il (not on Linux)
# lb (by --without-libbraille)
# xw (by --disable-x)

directory=`dirname "${0}"`
"${directory}/configure" \
   --disable-api \
   --disable-icu \
   --disable-gpm \
   --disable-polkit \
   --disable-x \
   \
   --without-libbraille \
   --with-braille-driver=-lt,-tt,-vd,-vr \
   \
   --disable-speech-support \
   \
   --without-bell-package \
   --without-leds-package \
   \
   --without-pcm-package \
   --without-midi-package \
   --without-fm-package \
   \
   --host=i386-elf \
   "${@}"
exit "${?}"
