#!/bin/bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2018 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.com/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"
addProgramParameter directory headersDirectory "the directory containing the headers"
parseProgramArguments "${@}"

set -e
cd "${headersDirectory}"

diff \
   <(ls -1 *.h | sort -u) \
   <(sed -n -e 's/^ *# *include *"\(.*\)" *$/\1/p' *.h | sort -u) \
   | sed -n -e 's/^> *//p' | sort -u

exit 0
