#!/bin/bash
. "$(dirname "${0}")/prologue.sh"

configureOptions=(
   --enable-relocatable-install
   --without-pgmprivs-package
   --without-libbraille
   --without-mikropuhe
   --without-swift
   --without-theta
   --disable-lisp-bindings
   --disable-ocaml-bindings
)

addSourceTreeOption
addBuildTreeOption
addInstallLocationOption
parseProgramArguments "${@}"

verifySourceTree
verifyBuildTree true
verifyInstallLocation

set -e
cd "${sourceTree}"
revisionIdentifier="$(./getrevid .)"
installTree="${installLocation}/REV-${revisionIdentifier}"
configureOptions+=("--with-execute-root=${installTree}")

cd "${buildTree}"
toRelativePath "${sourceTree}" sourcePath
"${sourcePath}/configure" --quiet "${configureOptions[@]}"
exit 0
