#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2014 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any
# later version. Please see the file LICENSE-GPL for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"

[ "${#}" -gt 0 ] || syntaxError "missing source root"
sourceRoot="${1}"
shift

[ "${#}" -eq 0 ] || syntaxError "too many parameters"

[ -e "${sourceRoot}" ] || semanticError "directory not found: ${sourceRoot}"
[ -d "${sourceRoot}" ] || semanticError "not a directory: ${sourceRoot}"
cd "${sourceRoot}" || semanticError "directory not usable: ${sourceRoot}"

if [ -d .git ]
then
   identifier="`git describe --tags --abbrev=8 --dirty='(modified)' --match='BRLTTY-*' 2>/dev/null`"
elif [ -d .svn ]
then
   identifier="`svnversion -n . 2>/dev/null`"
   [ "${identifier}" != "exported" ] || identifier=""
else
   identifier=""
fi

[ -n "${identifier}" ] || semanticError "build identifier not known"
echo "${identifier}"
exit 0
