#!/bin/bash -p
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2014 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any
# later version. Please see the file LICENSE-GPL for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"

outputFile=""
quoteIdentifier=false

while getopts ":o:q" option
do
   case "${option}"
   in
      o) outputFile="${OPTARG}";;
      q) quoteIdentifier=true;;

      :) syntaxError "missing value: -${OPTARG}";;
     \?) syntaxError "unknown option: -${OPTARG}";;
      *) syntaxError "unimplemented option: -${option}";;
   esac
done
shift $((OPTIND - 1))

[ "${#}" -gt 0 ] || syntaxError "missing source root"
sourceRoot="${1}"
shift

[ "${#}" -eq 0 ] || syntaxError "too many parameters"

[ -e "${sourceRoot}" ] || semanticError "directory not found: ${sourceRoot}"
[ -d "${sourceRoot}" ] || semanticError "not a directory: ${sourceRoot}"

if [ -d "${sourceRoot}/.git" ]
then
   revisionIdentifier="`git --work-tree="${sourceRoot}" describe --tags --abbrev=8 --dirty='M' --match='BRLTTY-*' 2>/dev/null`"
elif [ -d "${sourceRoot}/.svn" ]
then
   revisionIdentifier="`svnversion -n "${sourceRoot}" 2>/dev/null`"
   [ "${revisionIdentifier}" != "exported" ] || revisionIdentifier=""
else
   semanticError "unrecognized source repository type: ${sourceRoot}"
fi

[ -n "${revisionIdentifier}" ] || semanticError "revision identifier not known"
"${quoteIdentifier}" && revisionIdentifier='"'"${revisionIdentifier}"'"'

if [ -z "${outputFile}" ]
then
   echo "${revisionIdentifier}"
else
   if [ -e "${outputFile}" ]
   then
      [ -f "${outputFile}" ] || semanticError "not a file: ${outputFile}"
      [ -r "${outputFile}" ] || semanticError "file not readable: ${outputFile}"

      exec 3<"${outputFile}"
      read -u3 && {
         [ "${REPLY}" != "${revisionIdentifier}" ] || read -u3 || exit 0
      }
      exec 3<&-

      [ -w "${outputFile}" ] || semanticError "file not writable: ${outputFile}"
   else
      outputDirectory="$(dirname "${outputFile}")"
      [ -d "${outputDirectory}" ] || semanticError "not a directory: ${outputDirectory}"
      [ -w "${outputDirectory}" ] || semanticError "directory not writable: ${outputDirectory}"
   fi

   echo "${revisionIdentifier}" >"${outputFile}"
fi

exit 0
