#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2011 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any
# later version. Please see the file LICENSE-GPL for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"

outputFile=""
packageName=""

while getopts ":o:p:" option
do
   case "${option}"
   in
      o) outputFile="${OPTARG}";;
      p) packageName="${OPTARG}";;
      :) syntaxError "missing operand: -${OPTARG}";;
     \?) syntaxError "unknown option: -${OPTARG}";;
      *) syntaxError "unimplemented option: -${option}";;
   esac
done
shift `expr "${OPTIND}" - 1`

[ "${#}" -gt 0 ] || syntaxError "missing source root."
sourceRoot="${1}"
shift 1

[ "${#}" -eq 0 ] || syntaxError "too many parameters."

sourceRoot=`cd "${sourceRoot}" && pwd` || semanticError
buildRoot=`pwd`
[ "${buildRoot}" != "${sourceRoot}" ] || buildRoot=""

[ -n "${packageName}" ] || packageName=`basename "${sourceRoot}"`
[ -n "${outputFile}" ] || outputFile="${packageName}.pot"
[ "${outputFile#/}" != "${outputFile}" ] || outputFile="${initialDirectory}/${outputFile}"

xgettext -o - \
   --msgid-bugs-address=dave@mielke.cc --copyright-holder="The BRLTTY Developers" \
   --keyword=strtext:1 --flag=logMessage:2:c-format \
   `find "${sourceRoot}" "${buildRoot}" -name '*.c' -o -name '*.h'` |
sed >"${outputFile}" -e "
s/PACKAGE/${packageName}/
"
exit "${?}"
