#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2007 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation.  Please see the file COPYING for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"

[ "${#}" -eq 0 ] && syntaxError "missing output file."
headerFile="${1}"
shift

[ "${#}" -eq 0 ] && syntaxError "missing source directory."
sourceDirectory="${1}"
shift

[ "${#}" -eq 0 ] || syntaxError "too many parameters."

set -e
revisionNumber="`svnversion "${sourceDirectory}"`" || revisionNumber=
[ "${revisionNumber}" != "exported" ] || revisionNumber=
echo >"${headerFile}" "\"${revisionNumber}\""
exit 0
