#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2013 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any
# later version. Please see the file LICENSE-GPL for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"
needTemporaryDirectory

[ "${#}" -eq 0 ] && syntaxError "missing archive."
archiveFile="${1}"
[ "${archiveFile#/}" = "${archiveFile}" ] && archiveFile="${initialDirectory}/${archiveFile}"
shift

[ "${#}" -eq 0 ] || syntaxError "too many parameters."

set -e
mkdir SPECS SOURCES BUILD RPMS SRPMS
rpmbuild -ta --clean --define "_topdir ${temporaryDirectory}" --define "_tmppath ${temporaryDirectory}" "${archiveFile}"
mv -- SRPMS/*.rpm "${initialDirectory}"
mv -- RPMS/*/*.rpm "${initialDirectory}"
exit 0
