#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2008 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation.  Please see the file COPYING for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"

[ "${#}" -eq 0 ] && syntaxError "missing source root."
sourceRoot="${1}"
shift
cd "${sourceRoot}" || exit "${?}"
sourceRoot="`pwd`"

if [ "${#}" -eq 0 ]
then
   archiveName="`basename "${sourceRoot}"`"
else
   archiveName="${1}"
   shift
fi

if [ "${#}" -eq 0 ]
then
   archiveFile="${archiveName}.tar"
else
   archiveFile="${1}"
   shift
fi
[ "${archiveFile#/}" = "${archiveFile}" ] && archiveFile="${initialDirectory}/${archiveFile}"

[ "${#}" -eq 0 ] || syntaxError "too many parameters."

needTemporaryDirectory
set -e

cp -p -r -- "${sourceRoot}" "${archiveName}"
cd "${archiveName}"

./autogen
./configure --quiet --without-libbraille --without-flite --without-mikropuhe --without-speechd --without-swift --without-theta --without-viavoice

cd Documents
make -s clean
make -s
cd ..

specFile="brltty.spec"
mv -- "${specFile}" "${temporaryDirectory}"
make -s distclean
mv -- "${temporaryDirectory}/${specFile}" .

cd ..
tar --create --exclude=.svn --no-anchored --file "${archiveFile}" "${archiveName}"
exit 0
