#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2026 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/brltty-prologue.sh"

showProgramUsagePurpose() {
cat <<END_OF_PROGRAM_USAGE_PURPOSE
Convert a document from reStructured text to plain text.
END_OF_PROGRAM_USAGE_PURPOSE
}

addProgramParameter input rstFile "source document - reStructured text"
addProgramParameter output txtFile "generated document - plain text"
parseProgramArguments "${@}"

verifyInputFile $rstFile
verifyOutputFile $txtFile

needTemporaryDirectory
htmlFile="${temporaryDirectory}/document.html"

set -e
cd "${initialDirectory}"
rst2html --config "${programDirectory}/docutils.conf" -- "${rstFile}" "${htmlFile}"

sed --expression '
/<div .* id="contents"/,/<\/div>/d
' --in-place "${htmlFile}"

pandoc --from html --to plain --output "${txtFile}" -- "${htmlFile}"
exit 0
