#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the Linux console (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2004 by The BRLTTY Team. All rights reserved.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation.  Please see the file COPYING for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

cd "`dirname "${0}"`"
rootDirectory="`pwd`"
exec "${rootDirectory}/Programs/brltty" -L "${rootDirectory}/lib" -D "${rootDirectory}/data" -T "${rootDirectory}/BrailleTables" -C "${rootDirectory}/ContractionTables" "$@"
exit "${?}"
