#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2018 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.com/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"

[ -z "${LD_LIBRARY_PATH}" ] || LD_LIBRARY_PATH=":${LD_LIBRARY_PATH}"
LD_LIBRARY_PATH="${programDirectory}/Programs${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH

vgFile=""
vgDirectory="${BRLTTY_VALGRIND}"

[ -z "${vgDirectory}" ] || {
  [ ! -d "${vgDirectory}" ] || {
    [ ! -w "${vgDirectory}" ] || {
      vgFile="${vgDirectory}/$(basename "${1}")-$(date +%Y%m%d-%H%M%S).vg"
    }
  }
}

if [ -n "${vgFile}" ]
then
  set -- valgrind --log-file="${vgFile}" --leak-check=full --show-reachable=yes "${@}"
else
  set -- exec "${@}"
fi

"${@}"
exit "${?}"
