#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2020 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "$(dirname "${0}")/prologue.sh"

[ "${#}" -eq 0 ] && {
cat <<END_OF_USAGE
Usage: ${programName} command [argument ...]
Execute the specified command with the specified arguments. If not root
then execute the command as root via sudo.

Environment Variables:
  <COMMAND>_VALGRIND_DIRECTORY=path
    If set then write a valgrind memory usage log to a file named
    <command>-yyyymmdd-HHMMSS.vg in the specified directory.
  <COMMAND>_USER_NAME=user
    If set then execute the command as the specified user. The
    user's primary group and supplementary groups will also be set.
END_OF_USAGE
exit 0
}

commandName="${1}"
shift 1

readonly commandPath="$(type -P "${commandName}")"
[ -n "${commandPath}" ] || semanticError "command not found: ${commandName}"
readonly commandName="${commandPath##*/}"
set -- "${commandPath}" "${@}"

readonly variablePrefix="${commandName^^?}"
getVariable "${variablePrefix}_VALGRIND_DIRECTORY" vgDirectory
getVariable "${variablePrefix}_USER_NAME" asUser

[ -n "${LD_LIBRARY_PATH}" ] && LD_LIBRARY_PATH=":${LD_LIBRARY_PATH}"
LD_LIBRARY_PATH="${programDirectory}/Programs${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH

[ -n "${vgDirectory}" ] && {
   [ -e "${vgDirectory}" ] || semanticError "directory not found: ${vgDirectory}"
   [ -d "${vgDirectory}" ] || semanticError "not a directory: ${vgDirectory}"
   [ -w "${vgDirectory}" ] || semanticError "directory not writable: ${vgDirectory}"

   vgFile="${vgDirectory}/${commandName}-$(date +%Y%m%d-%H%M%S).vg"
   programMessage "valgrind log: ${vgFile}"

   set -- valgrind \
       --log-file="${vgFile}" \
       --leak-check=full \
       --show-reachable=yes \
       "${@}"
}

[ -n "${asUser}" ] && {
   id -u -- "${asUser}" >/dev/null 2>&1 || semanticError "unknown user: ${asUser}"
   set -- capsh \
       --caps=cap_sys_admin,cap_sys_tty_config,cap_setuid,cap_setgid=ep \
       --user="${asUser}" \
       --caps=cap_setuid,cap_setgid-ep \
       -- -c "${*}"
}

[ "$(id -u)" -eq 0 ] || set -- sudo -E -- "${@}"
exec "${@}"
exit "${?}"
