#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2008 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any
# later version. Please see the file LICENSE-GPL for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

set -e
cd "`dirname "${0}"`"

BRLTTY_LIBRARY_DIRECTORY="../lib"
BRLTTY_DATA_DIRECTORY="../data"
BRLTTY_TABLES_DIRECTORY="../Tables"
export BRLTTY_LIBRARY_DIRECTORY BRLTTY_DATA_DIRECTORY BRLTTY_TABLES_DIRECTORY

exec "Programs/brltty" -E "$@"
exit "${?}"
