#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2021 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"
setSourceRoot
setBuildRoot

export BRLTTY_TABLES_DIRECTORY="${BRLTTY_SOURCE_ROOT}/Tables"
export BRLTTY_DRIVERS_DIRECTORY="${BRLTTY_BUILD_ROOT}/lib"
export BRLTTY_LOCALE_DIRECTORY="${BRLTTY_BUILD_ROOT}/Messages/locale"

exec "${programDirectory}/run-command" "${BRLTTY_BUILD_ROOT}/Programs/brltty" -E "${@}"
exit "${?}"
