#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2020 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/prologue.sh"
addProgramOption u flag noUsers "don't allow switching to the default unprivileged user"
addProgramOption g flag noGroups "don't allow switching to the writable group or joining required groups"
addProgramOption o flag noOwnership "don't allow claiming group ownership of the state directories"
addProgramOption p flag noPermissions "don't allow adding group permissions to the state directories"
addProgramOption m flag noModules "don't allow installing kernel modules"
addProgramOption i flag noInput "don't allow injecting input characters"
addProgramOption s flag noSpeaker "don't allow using the built-in PC speaker"
addProgramOption d flag noDevices "don't allow creating special device files"
addProgramParameter executable executablePath "the path to the executable"

noUsers=false
noGroups=false
noOwnership=false
noPermissions=false
noModules=false
noInput=false
noSpeaker=false
noDevices=false
parseProgramArguments "${@}"

[ -e "${executablePath}" ] || semanticError "file not found: ${executablePath}"
[ -f "${executablePath}" ] || semanticError "not a file: ${executablePath}"
[ -x "${executablePath}" ] || semanticError "file not executable: ${executablePath}"

capabilitiesList=()
addCapability() {
   capabilitiesList[${#capabilitiesList[*]}]="${1}"
}

"${noUsers}" || addCapability "cap_setuid"
"${noGroups}" || addCapability "cap_setgid"
"${noOwnership}" || addCapability "cap_chown"
"${noPermissions}" || addCapability "cap_fowner"
"${noModules}" || addCapability "cap_sys_module"
"${noInput}" || addCapability "cap_sys_admin"
"${noSpeaker}" || addCapability "cap_sys_tty_config"
"${noDevices}" || addCapability "cap_mknod"

capabilitiesOperand="${capabilitiesList[*]}"
capabilitiesOperand="${capabilitiesOperand// /,}"
capabilitiesOperand+="+p"
set -- setcap "${capabilitiesOperand}" "${executablePath}"

[ "$(id -u)" -eq 0 ] || set -- sudo -- "${@}"
"${@}"
exit "${?}"
