#!/bin/bash

. "$(dirname "${0}")/prologue.sh"
addSourceTreeOption
addBuildTreeOption
parseProgramArguments "${@}"

verifySourceTree
verifyBuildTree

set -e
getInstallTree installTree
installSubdirectory="$(basename "${installTree}")"
installLocation="$(dirname "${installTree}")"
installSymlink="${installLocation}/current"

[ "$(readlink "${installSymlink}")" = "${installSubdirectory}" ] || {
   sudo rm -- "${installSymlink}"
   sudo ln --symbolic -- "${installSubdirectory}" "${installSymlink}"
}

exit 0
