#!/bin/bash

. "$(dirname "${0}")/prologue.sh"
addSourceTreeOption
addBuildTreeOption
parseProgramArguments "${@}"

verifySourceTree
verifyBuildTree

set -e
getInstallTree installTree
installLocation="$(dirname "${installTree}")"
installDirectory="$(basename "${installTree}")"
sudo rm -- "${installLocation}/current"
sudo ln --symbolic -- "${installDirectory}" "${installLocation}/current"
exit 0
