# Dependencies for trcp.o:
trcp.o: $(SRC_DIR)/trcp.c
trcp.o: $(BLD_TOP)config.h
trcp.o: $(SRC_DIR)/unicode.h
trcp.o: $(SRC_TOP)Programs/options.h

# Dependencies for unicode.o:
unicode.o: $(SRC_DIR)/unicode.c
unicode.o: $(BLD_TOP)config.h
unicode.o: $(SRC_DIR)/unicode.h
unicode.o: $(SRC_DIR)/unicode-table.h
unicode.o: $(SRC_DIR)/iso-8859-1.h
unicode.o: $(SRC_DIR)/iso-8859-2.h
unicode.o: $(SRC_DIR)/iso-8859-3.h
unicode.o: $(SRC_DIR)/iso-8859-4.h
unicode.o: $(SRC_DIR)/iso-8859-5.h
unicode.o: $(SRC_DIR)/iso-8859-6.h
unicode.o: $(SRC_DIR)/iso-8859-7.h
unicode.o: $(SRC_DIR)/iso-8859-8.h
unicode.o: $(SRC_DIR)/iso-8859-9.h
unicode.o: $(SRC_DIR)/iso-8859-10.h
unicode.o: $(SRC_DIR)/iso-8859-13.h
unicode.o: $(SRC_DIR)/iso-8859-14.h
unicode.o: $(SRC_DIR)/iso-8859-15.h
unicode.o: $(SRC_DIR)/iso-8859-16.h
unicode.o: $(SRC_DIR)/cp-37.h
unicode.o: $(SRC_DIR)/cp-424.h
unicode.o: $(SRC_DIR)/cp-437.h
unicode.o: $(SRC_DIR)/cp-500.h
unicode.o: $(SRC_DIR)/cp-737.h
unicode.o: $(SRC_DIR)/cp-775.h
unicode.o: $(SRC_DIR)/cp-850.h
unicode.o: $(SRC_DIR)/cp-852.h
unicode.o: $(SRC_DIR)/cp-855.h
unicode.o: $(SRC_DIR)/cp-856.h
unicode.o: $(SRC_DIR)/cp-857.h
unicode.o: $(SRC_DIR)/cp-860.h
unicode.o: $(SRC_DIR)/cp-861.h
unicode.o: $(SRC_DIR)/cp-862.h
unicode.o: $(SRC_DIR)/cp-863.h
unicode.o: $(SRC_DIR)/cp-864.h
unicode.o: $(SRC_DIR)/cp-865.h
unicode.o: $(SRC_DIR)/cp-866.h
unicode.o: $(SRC_DIR)/cp-869.h
unicode.o: $(SRC_DIR)/cp-874.h
unicode.o: $(SRC_DIR)/cp-875.h
unicode.o: $(SRC_DIR)/cp-1006.h
unicode.o: $(SRC_DIR)/cp-1026.h
unicode.o: $(SRC_DIR)/cp-1250.h
unicode.o: $(SRC_DIR)/cp-1251.h
unicode.o: $(SRC_DIR)/cp-1252.h
unicode.o: $(SRC_DIR)/cp-1253.h
unicode.o: $(SRC_DIR)/cp-1254.h
unicode.o: $(SRC_DIR)/cp-1255.h
unicode.o: $(SRC_DIR)/cp-1256.h
unicode.o: $(SRC_DIR)/cp-1257.h
unicode.o: $(SRC_DIR)/cp-1258.h
unicode.o: $(SRC_DIR)/koi8-r.h
unicode.o: $(SRC_DIR)/koi8-ru.h
unicode.o: $(SRC_DIR)/koi8-u.h

