#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2018 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.com/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

# Simple BrlTTY GenericSay helper script.
# It should be installed as "/usr/local/bin/say".

# If your speech synthesizer does not require any special initialization
# sequences, and if you either are satisfied with its default settings or
# don't know how to change them, then this helper script is for you. It
# does no more than simply send the text to be spoken directly to your
# synthesizer. Note that, being totally general, it cannot, and does
# not, implement the mute function. All you need to do is:
# - Set the device (see "device=" line below).
# - Install the script (as /usr/local/bin/say).

device=/dev/ttyS0
exec cat >"${device}"
exit $?
