#!/bin/bash

export BRLTTY_API_PARAMETERS=$(getarg brltty.api_parameters=)
export BRLTTY_ATTRIBUTES_TABLE=$(getarg brltty.attributes_table=)
export BRLTTY_BRAILLE_DEVICE=$(getarg brltty.braille_device=)
export BRLTTY_BRAILLE_DRIVER=$(getarg brltty.braille_driver=)
export BRLTTY_BRAILLE_PARAMETERS=$(getarg brltty.braille_parameters=)
export BRLTTY_CONFIGURATION_FILE=$(getarg brltty.configuration_file=)
export BRLTTY_CONTRACTION_TABLE=$(getarg brltty.contraction_table=)
export BRLTTY_MIDI_DEVICE=$(getarg brltty.midi_device=)
export BRLTTY_PCM_DEVICE=$(getarg brltty.pcm_device=)
export BRLTTY_PREFERENCES_FILE=$(getarg brltty.preferences_file=)
export BRLTTY_RELEASE_DEVICE=$(getarg brltty.release_device=)
export BRLTTY_SCREEN_DRIVER=$(getarg brltty.screen_driver=)
export BRLTTY_SCREEN_PARAMETERS=$(getarg brltty.screen_parameters=)
export BRLTTY_SPEECH_DRIVER=$(getarg brltty.speech_driver=)
export BRLTTY_SPEECH_INPUT=$(getarg brltty.speech_input=)
export BRLTTY_SPEECH_PARAMETERS=$(getarg brltty.speech_parameters=)
export BRLTTY_TEXT_TABLE=$(getarg brltty.text_table=)
