#!/bin/sh

mkhlpfie()
{
fno=$1
cols=$2
cells=$3
colsm1=`expr $cols - 1`
gcc -DGENHLP -I../.. -E braille.c | ./hlptrans.py \
| cat brltty_helpmodel.txt - \
| sort -t: -s -k 1,1 | cut -d: -f 2- \
| sed "s/<COLS>/${cols}/g" | sed "s/<COLS-1>/${colsm1}/g" \
| sed "s/<CELLS>/${cells}/g" \
> brlttyhlp${fno}.txt
}

mkhlpfie 0 40 44
mkhlpfie 1 66 70
