GRADLE_COMMAND = ./gradlew -q

GRADLE_ROOT_NAME = brltty
GRADLE_CORE_NAME = core
GRADLE_APP_NAME = app

GRADLE_DEBUG_VARIANT = debug
GRADLE_RELEASE_VARIANT = release

GRADLE_PACKAGE_EXTENSION = apk
GRADLE_BUNDLE_EXTENSION = aab

GRADLE_BUILD_DIRECTORY = app/build
GRADLE_OUTPUT_DIRECTORY = $(GRADLE_BUILD_DIRECTORY)/outputs
GRADLE_PACKAGE_DIRECTORY = $(GRADLE_OUTPUT_DIRECTORY)/apk
GRADLE_BUNDLE_DIRECTORY = $(GRADLE_OUTPUT_DIRECTORY)/bundle

GRADLE_REPORT_DIRECTORY = $(GRADLE_BUILD_DIRECTORY)/reports
GRADLE_REPORT_NAME = lint
GRADLE_REPORT_TYPE = results
GRADLE_REPORT_EXTENSION = html

GRADLE_DUMP_COMMAND = aapt dump
GRADLE_DUMP_EXTENSION = dump

GRADLE_DEBUG_PACKAGE = $(GRADLE_PACKAGE_DIRECTORY)/$(GRADLE_DEBUG_VARIANT)/$(GRADLE_APP_NAME)-$(GRADLE_DEBUG_VARIANT).$(GRADLE_PACKAGE_EXTENSION)
GRADLE_RELEASE_PACKAGE = $(GRADLE_PACKAGE_DIRECTORY)/$(GRADLE_RELEASE_VARIANT)/$(GRADLE_APP_NAME)-$(GRADLE_RELEASE_VARIANT).$(GRADLE_PACKAGE_EXTENSION)

GRADLE_DEBUG_BUNDLE = $(GRADLE_BUNDLE_DIRECTORY)/$(GRADLE_DEBUG_VARIANT)/$(GRADLE_APP_NAME)-$(GRADLE_DEBUG_VARIANT).$(GRADLE_BUNDLE_EXTENSION)
GRADLE_RELEASE_BUNDLE = $(GRADLE_BUNDLE_DIRECTORY)/$(GRADLE_RELEASE_VARIANT)/$(GRADLE_APP_NAME)-$(GRADLE_RELEASE_VARIANT).$(GRADLE_BUNDLE_EXTENSION)

GRADLE_DEBUG_REPORT = $(GRADLE_REPORT_DIRECTORY)/$(GRADLE_REPORT_NAME)-$(GRADLE_REPORT_TYPE)-$(GRADLE_DEBUG_VARIANT).$(GRADLE_REPORT_EXTENSION)
GRADLE_RELEASE_REPORT = $(GRADLE_REPORT_DIRECTORY)/$(GRADLE_REPORT_NAME)-$(GRADLE_REPORT_TYPE)-$(GRADLE_RELEASE_VARIANT).$(GRADLE_REPORT_EXTENSION)

