GRADLE_COMMAND = ./gradlew -q

GRADLE_ROOT_NAME = brltty
GRADLE_CORE_NAME = core
GRADLE_APP_NAME = app
GRADLE_REPORT_NAME = lint

GRADLE_DEBUG_VARIANT = debug
GRADLE_RELEASE_VARIANT = release

GRADLE_PACKAGE_EXTENSION = apk
GRADLE_BUNDLE_EXTENSION = aab
GRADLE_REPORT_EXTENSION = html

GRADLE_BUILD_SUBDIRECTORY = app/build
GRADLE_REPORT_SUBDIRECTORY = $(GRADLE_BUILD_SUBDIRECTORY)/reports
GRADLE_OUTPUT_SUBDIRECTORY = $(GRADLE_BUILD_SUBDIRECTORY)/outputs
GRADLE_PACKAGE_SUBDIRECTORY = $(GRADLE_OUTPUT_SUBDIRECTORY)/apk
GRADLE_BUNDLE_SUBDIRECTORY = $(GRADLE_OUTPUT_SUBDIRECTORY)/bundle

GRADLE_DEBUG_PACKAGE = $(GRADLE_PACKAGE_SUBDIRECTORY)/$(GRADLE_DEBUG_VARIANT)/$(GRADLE_APP_NAME)-$(GRADLE_DEBUG_VARIANT).$(GRADLE_PACKAGE_EXTENSION)
GRADLE_RELEASE_PACKAGE = $(GRADLE_PACKAGE_SUBDIRECTORY)/$(GRADLE_RELEASE_VARIANT)/$(GRADLE_APP_NAME)-$(GRADLE_RELEASE_VARIANT).$(GRADLE_PACKAGE_EXTENSION)

GRADLE_DEBUG_BUNDLE = $(GRADLE_BUNDLE_SUBDIRECTORY)/$(GRADLE_DEBUG_VARIANT)/$(GRADLE_APP_NAME)-$(GRADLE_DEBUG_VARIANT).$(GRADLE_BUNDLE_EXTENSION)
GRADLE_RELEASE_BUNDLE = $(GRADLE_BUNDLE_SUBDIRECTORY)/$(GRADLE_RELEASE_VARIANT)/$(GRADLE_APP_NAME)-$(GRADLE_RELEASE_VARIANT).$(GRADLE_BUNDLE_EXTENSION)

GRADLE_DEBUG_REPORT = $(GRADLE_REPORT_SUBDIRECTORY)/$(GRADLE_REPORT_NAME)-results-$(GRADLE_DEBUG_VARIANT).$(GRADLE_REPORT_EXTENSION)
GRADLE_RELEASE_REPORT = $(GRADLE_REPORT_SUBDIRECTORY)/$(GRADLE_REPORT_NAME)-results-$(GRADLE_RELEASE_VARIANT).$(GRADLE_REPORT_EXTENSION)

