#!/bin/bash

installTree="/brltty/current"
. "${installTree}/bin/brltty-prologue.sh"

addTestModeOption
addProgramOption A flag allActions "perform all of the actions"
addProgramOption p flag hostPackages "install the host packages"
addProgramOption e flag etcFiles "install the /etc/ files"
addProgramOption k flag apiKey "generate the BrlAPI access key"
addProgramOption l flag sharedLibraries "configure the shared libraries"
addProgramOption u flag udevReload "reload the Udev rules"
addProgramOption s flag systemdUnits "configure the Systemd units"
parseProgramArguments "${@}"

actionFlags=(hostPackages etcFiles apiKey sharedLibraries udevReload systemdUnits)
verifyActionFlags allActions "${actionFlags[@]}"

performAction_hostPackages() {
   local packages=()
   local line

   while read line
   do
      packages+=("${line}")
   done <"${installTree}/etc/host-packages"

   [ "${#packages[*]}" -eq 0 ] || {
      executeHostCommand apt --yes --quiet --quiet --quiet install -- "${packages[@]}"
   }
}

performAction_etcFiles() {
   executeHostCommand tar --extract --file "${installTree}/etc.tar" --directory "/"
}

performAction_apiKey() {
   local apiKeyFile="/etc/brlapi.key"
   executeHostCommand "${installTree}/bin/brltty-genkey" -q -f "${apiKeyFile}"
   executeHostCommand chmod u=rw,go=r "${apiKeyFile}"
}

performAction_sharedLibraries() {
   executeHostCommand ldconfig
}

performAction_udevReload() {
   executeHostCommand udevadm control --reload
}

performAction_systemdUnits() {
   executeHostCommand systemctl daemon-reload
   local unit

   for unit in "brltty@canute.path"
   do
      executeHostCommand systemctl enable "${unit}"
      executeHostCommand systemctl start "${unit}"
   done
}

[ "$(id -u)" -eq 0 ] || semanticError "not executing as root"
set -e

for action in "${actionFlags[@]}"
do
   ! "${!action}" || {
      "performAction_${action}"
   }
done

exit 0
