#!/bin/bash
. /brltty/current/libexec/canute-prologue.sh
shopt -s extglob

addTestModeOption
addProgramOption A flag allActions "perform all of the actions"
addProgramOption P flag unwantedPackages "remove unwanted packages"
addProgramOption p flag requiredPackages "install required packages"
addProgramOption e flag etcFiles "install the /etc/ files"
addProgramOption k flag apiKey "generate the BrlAPI access key"
addProgramOption l flag sharedLibraries "configure the shared libraries"
addProgramOption u flag udevReload "reload the Udev rules"
addProgramOption s flag systemdUnits "configure the Systemd units"
addProgramOption d flag setDefault "set the default target to boot"
parseProgramArguments "${@}"

actionFlags=(unwantedPackages requiredPackages etcFiles apiKey sharedLibraries udevReload systemdUnits setDefault)
verifyActionFlags allActions "${actionFlags[@]}"

processPackages() {
   local type="${1}"
   shift 1

   local packagesFile="${installTree}/etc/${type}-packages"
   verifyInputFile "${packagesFile}"

   local packages=()
   local name

   while read name
   do
      name="${name##*( )}"
      [ -n "${name}" ] || continue
      [ "${name:0:1}" != "#" ] || continue
      name="${name%%*( )}"

      logNote "${type} package: ${name}"
      packages+=("${name}")
   done <"${packagesFile}"

   [ "${#packages[*]}" -eq 0 ] || {
      executeHostCommand "${@}" "${packages[@]}"
   }
}

performAction_unwantedPackages() {
   processPackages unwanted apt --yes --quiet --quiet --quiet remove --
}

performAction_requiredPackages() {
   processPackages required apt --yes --quiet --quiet --quiet install --
}

performAction_etcFiles() {
   executeHostCommand tar --extract --file "${installTree}/etc.tar" --directory "/"
}

performAction_apiKey() {
   local apiKeyFile="/etc/brlapi.key"
   executeHostCommand "${installTree}/bin/brltty-genkey" -q -f "${apiKeyFile}"
   executeHostCommand chmod u=rw,go=r "${apiKeyFile}"
}

performAction_sharedLibraries() {
   local file lines=""

   while read file
   do
      [ -z "${lines}" ] || lines+=$'\n'
      lines+="${file}"
   done < <(find "${installTree}/" -type f \( -name "*.so" -o -name "*.so.*" \))

   sed <<<"${lines}" --regexp-extended --expression '
      s%/[^/]*$%%
      /\/brltty$/d
   ' | sort | uniq >"${ldConfigurationFile}"

   executeHostCommand ldconfig
}

performAction_udevReload() {
   executeHostCommand udevadm control --reload
}

performAction_systemdUnits() {
   executeHostCommand systemctl --quiet daemon-reload
   local unit

   for unit in "${canuteSystemdUnit}"
   do
      ! systemctl --quiet is-active "${unit}" || executeHostCommand systemctl --quiet stop "${unit}"
      executeHostCommand systemctl --quiet start "${unit}"
      systemctl --quiet is-enabled "${unit}" || executeHostCommand systemctl --quiet enable "${unit}"
   done
}

performAction_setDefault() {
   executeHostCommand systemctl --quiet set-default multi-user.target
}

"${testMode}" || [ "$(id -u)" -eq 0 ] || semanticError "not executing as root"
set -e

for action in "${actionFlags[@]}"
do
   ! "${!action}" || {
      "performAction_${action}"
   }
done

exit 0
