#!/bin/bash
. /brltty/current/libexec/canute-prologue.sh

parseProgramArguments "${@}"
set -e

eval $(dbus-launch --sh-syntax --exit-with-session)
export GTK_MODULES=gail:atk-bridge

atspiDirectory="/usr/lib/at-spi2-core"
"${atspiDirectory}/at-spi-bus-launcher" &
"${atspiDirectory}/at-spi2-registryd" &
sleep 3

canuteSetSession canute
brlttyPath="${installTree}/bin"
"${brlttyPath}/xbrlapi"
"${brlttyPath}/brltty" -N -f "${installTree}/etc/brltty-startx.conf"

marco &
exec gnome-terminal --wait --title "Canute Interactive Session" -- "${installTree}/libexec/canute-shell"
exit "${?}"
