#!/bin/bash
. "$(dirname "${0}")/../prologue.sh"
. "${programDirectory}/make-prologue.sh"

addTestModeOption
addSourceTreeOption
addBuildTreeOption
parseProgramArguments "${@}"

verifySourceTree
verifyBuildTree

set -e
getInstallTree installTree

for sourceDirectory in Files/*
do
   targetDirectory="${installTree}/${sourceDirectory#*/}"
   executeHostCommand sudo cp -- "${topDirectory}/${sourceDirectory}/"* "${targetDirectory}/"
done

for subdirectory in etc
do
   executeHostCommand sudo tar --create --file "${installTree}/${subdirectory}.tar" "${subdirectory}"
done

exit 0
