#!/bin/bash
. "$(dirname "${0}")/../prologue.sh"

configureOptions=(
   --enable-relocatable-install
   --without-pgmprivs-package
   --without-libbraille
   --without-mikropuhe
   --without-swift
   --without-theta
   --disable-lisp-bindings
   --disable-ocaml-bindings
)

addTestModeOption
addSourceTreeOption
addBuildTreeOption
addInstallLocationOption
parseProgramArguments "${@}"

verifySourceTree
verifyBuildTree true
verifyInstallLocation

set -e
revisionIdentifier="$("${sourceTree}/getrevid" "${sourceTree}")"
installTree="${installLocation}/REV-${revisionIdentifier}"
configureOptions+=("--with-execute-root=${installTree}")

executeHostCommand cd "${buildTree}"
toRelativePath "${sourceTree}" sourcePath
executeHostCommand "${sourcePath}/configure" --quiet "${configureOptions[@]}"
exit 0
