#!/bin/bash
. /brltty/current/libexec/canute-prologue.sh

makeLink() {
   local linkName="${1}"

   local linkPath="${apiLinksDirectory}/${linkName}"
   local linkTarget="$(realpath --relative-to "${apiLinksDirectory}" -- "${targetDirectory}")"
   ! [ -e "${linkPath}" ] || executeHostCommand sudo rm -- "${linkPath}"
   executeHostCommand sudo ln --symbolic -- "${linkTarget}" "${linkPath}"
}

addTestModeOption
parseProgramArguments "${@}"
set -e

while read targetDirectory
do
   case "${targetDirectory}"
   in
      *java* | *jni*) makeLink jni;;
      *python*) makeLink python;;
      *tcl*) makeLink tcl;;
   esac
done <"${ldConfigurationFile}"

while read jarFile
do
   targetDirectory="$(dirname "${jarFile}")"
   makeLink java
done < <(find "${installTree}/" -type f -name "*.jar")

exit 0
