#!/bin/bash
. "$(dirname "${0}")/../prologue.sh"
. "${programDirectory}/make-prologue.sh"

addTestModeOption
addSourceTreeOption
addBuildTreeOption
parseProgramArguments "${@}"

verifySourceTree
verifyBuildTree

set -e
getInstallTree installTree
testDirectory "${installTree}" || semanticError "install tree not found: ${installTree}"

installSubdirectory="$(basename "${installTree}")"
installLocation="$(dirname "${installTree}")"

makeSymbolicLink "${installLocation}/current" "${installSubdirectory}"
executeHostCommand sudo "${installTree}/libexec/canute-setup" -q -l
exit 0
