#!/bin/bash
. /brltty/current/libexec/canute-prologue.sh
. "${programDirectory}/make-prologue.sh"

makeBindingsLink() {
   local linkName="${1}"

   local linkPath="${apiLinksDirectory}/${linkName}"
   local linkTarget="$(realpath --relative-to "${apiLinksDirectory}" -- "${targetDirectory}")"

   makeSymbolicLink "${linkPath}" "${linkTarget}"
}

addTestModeOption
parseProgramArguments "${@}"
set -e

while read targetDirectory
do
   case "${targetDirectory}"
   in
      *java* | *jni*) makeBindingsLink jni;;
      *python*) makeBindingsLink python;;
      *tcl*) makeBindingsLink tcl;;
   esac
done <"${ldConfigurationFile}"

while read jarFile
do
   targetDirectory="$(dirname "${jarFile}")"
   makeBindingsLink java
done < <(find "${installTree}/" -type f -name "*.jar")

exit 0
