#!/bin/bash

programName="${0##*/}"

showUsageSummary() {
cat <<END-OF-USAGE-SUMMARY
Usage: ${programName} [-option ...]

The following options may be specified:
  -a name  the name of the archive
  -h       show this command line usage summary, and then exit
  -l url   the location containing the archive
END-OF-USAGE-SUMMARY
}

programMessage() {
   local message="${1}"

   echo >&2 "${programName}: ${message}"
}

syntaxError() {
   local message="${1}"

   programMessage "${message}"
   exit 2
}

getFile() {
   local file="${1}"

   wget --quiet --output-document "${file}" -- "${archiveLocation}/${file}"
}

needTemporaryDirectory() {
   [ -n "${TMPDIR}" -a -d "${TMPDIR}" -a -r "${TMPDIR}" -a -w "${TMPDIR}" -a -x "${TMPDIR}" ] || export TMPDIR="/tmp"
   temporaryDirectory="$(mktemp -d "${TMPDIR}/${programName}.$(date +"%Y%m%d-%H%M%S").XXXXXX")"
}

removeTemporaryDirectory() {
   set +e
   cd /
   rm -f -r -- "${temporaryDirectory}"
}

showUsage=false
archiveLocation="https://brltty.app/archive/Canute"
archiveName="canute-brltty.tar.gz"

while getopts ":a:hl:" option
do
   case "${option}"
   in
      a) archiveName="${OPTARG}";;
      h) showUsage=true;;
      l) archiveLocation="${OPTARG}";;

      :) syntaxError "missing operand: -${OPTARG}";;
     \?) syntaxError "unrecognized option: -${OPTARG}";;
      *) syntaxError "unimplemented option: -${option}";;
   esac
done

shift $((OPTIND - 1))
[ "${#}" -eq 0 ] || syntaxError "too many parameters"

"${showUsage}" && {
   showUsageSummary
   exit 0
}

[ "$(id -u)" -eq 0 ] || semanticError "not executing as root"
set -e

needTemporaryDirectory
trap removeTemporaryDirectory exit

cd "${temporaryDirectory}"
getFile "${archiveName}"

tar --extract --absolute-names --file "${archiveName}" --directory "/"
"/brltty/current/libexec/canute-setup" -A

exit 0
