#!/bin/bash

programName="${0##*/}"

defaultArchiveLocation="https://brltty.app/archive/Canute"
defaultArchiveName="canute-brltty.tar.gz"

showUsageSummary() {
cat <<END-OF-USAGE-SUMMARY
Install or upgrade the Raspbian Canute software.
Copyright © 2022 by Bristol Braille Technology CIC

Usage: ${programName} [-option ...]
The following options may be specified:
  -h       show this command line usage summary, and then exit
  -a name  the name of the archive (${defaultArchiveName})
  -l url   the location containing the archive (${defaultArchiveLocation})

This script must be executed as root on a Raspbian system.
END-OF-USAGE-SUMMARY
}

programMessage() {
   local message="${1}"

   echo >&2 "${programName}: ${message}"
}

syntaxError() {
   local message="${1}"

   programMessage "${message}"
   exit 2
}

semanticError() {
   local message="${1}"

   programMessage "${message}"
   exit 3
}

downloadFile() {
   local file="${1}"

   wget --quiet --output-document "${file}" -- "${archiveLocation}/${file}"
}

needTemporaryDirectory() {
   [ -n "${TMPDIR}" -a -d "${TMPDIR}" -a -r "${TMPDIR}" -a -w "${TMPDIR}" -a -x "${TMPDIR}" ] || export TMPDIR="/tmp"
   temporaryDirectory="$(mktemp -d "${TMPDIR}/${programName}.$(date +"%Y%m%d-%H%M%S").XXXXXX")"
}

removeTemporaryDirectory() {
   set +e
   cd /
   rm -f -r -- "${temporaryDirectory}"
}

showUsage=false
archiveLocation="${defaultArchiveLocation}"
archiveName="${defaultArchiveName}"

while getopts ":ha:l:" option
do
   case "${option}"
   in
      h) showUsage=true;;
      a) archiveName="${OPTARG}";;
      l) archiveLocation="${OPTARG}";;

      :) syntaxError "missing operand: -${OPTARG}";;
     \?) syntaxError "unrecognized option: -${OPTARG}";;
      *) syntaxError "unimplemented option: -${option}";;
   esac
done

shift $((OPTIND - 1))
[ "${#}" -eq 0 ] || syntaxError "too many parameters"

"${showUsage}" && {
   showUsageSummary
   exit 0
}

[ -f "/usr/bin/raspi-config" ] || semanticError "not Raspbian"
[ "$(id -u)" -eq 0 ] || semanticError "not executing as root"
set -e

needTemporaryDirectory
trap removeTemporaryDirectory exit
cd "${temporaryDirectory}"

programMessage "downloading archive"
downloadFile "${archiveName}"

programMessage "unpacking archive"
tar --extract --absolute-names --file "${archiveName}" --directory "/"

"/brltty/current/libexec/canute-setup" -A
exit 0
