#!/bin/bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2025 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "$(dirname "${0}")/../prologue.sh"
toolName="brltty-ktb"

handleInitialHelpOption "${@}" <<END-OF-HELP
Check a key table for errors.

Syntax: ${programName} {-h | [-option ...] table}

All of the options, as well as the table name, are passed through to ${toolName}.
To see its usage summary, use its --help long option.
END-OF-HELP

setBuildRoot
set -e

cd "${buildRoot}/Programs"
make --silent "${toolName}"
"./${toolName}" -T../Tables -D../lib -a "${@}"
exit 0
