#!/bin/bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2025 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/../prologue.sh"
addProgramParameter table tableName "the key table name"
optionalProgramParameters
addProgramParameter driver brailleDriver "the braille driver code" "a keyboard table"
parseProgramArguments "${@}"

setSourceRoot
setBuildRoot

commandArguments=(--list)
commandArguments+=(--tables-directory "${sourceRoot}/Tables")
commandArguments+=(--drivers-directory "${buildRoot}/lib")
[ -n "${brailleDriver}" ] && commandArguments+=(--braille-driver "${brailleDriver}")
commandArguments+=(-- "${tableName}")

exec "${sourceRoot}/run-command" brltty-ktb "${commandArguments[@]}"
exit "${?}"
