#!/bin/bash

topDirectory="$(dirname "${0}")/.."
make --silent -C "${topDirectory}" clone
. "${topDirectory}/prologue.sh"

makeTarget() {
   local target="${1}"

   logTask "making target: ${target}"
   executeHostCommand make --silent -- "${target}"
}

addTestModeOption
addProgramOption A flag allActions "perform all of the actions"
addProgramOption u flag makeUnconfigure "unconfigure BRLTTY"
addProgramOption c flag makeConfigure "configure BRLTTY"
addProgramOption b flag makeBuild "build BRLTTY"
addProgramOption i flag makeInstall "install BRLTTY"
addProgramOption l flag makeCurrent "set the \"current\" link"
addProgramOption a flag makeArchives "make the archives"
parseProgramArguments "${@}"
verifyActionFlags allActions makeUnconfigure makeConfigure makeBuild makeInstall makeCurrent makeArchives

set -e
executeHostCommand cd "${topDirectory}"

! "${makeUnconfigure}" || makeTarget unconfigure
! "${makeConfigure}" || makeTarget configure
! "${makeBuild}" || makeTarget build
! "${makeInstall}" || makeTarget install
! "${makeCurrent}" || makeTarget current

! "${makeArchives}" || {
   executeHostCommand rm -f -- *.tar
   makeTarget gzip-archive
   makeTarget bzip2-archive
   makeTarget xz-archive
}

exit 0
