#!/bin/bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2021 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "$(dirname "${0}")/../prologue.sh"
setBuildRoot

defaultBuildRoot="${BRLTTY_BUILD_ROOT}"
defaultModuleName="brltty"
variableNames=()

processExtraProgramParameters() {
   variableNames+=( "${@}" )
}

addProgramOption b string.directory buildRoot "the root directory of the build" "${defaultBuildRoot}"
addProgramOption m string.moudle moduleName "the name of the module" "${defaultModuleName}"
optionalProgramParameters
parseProgramArguments "${@}"

[ -n "${buildRoot}" ] || buildRoot="${defaultBuildRoot}"
[ -n "${moduleName}" ] || moduleName="${defaultModuleName}"

pkgConfig() {
   pkg-config "${@}" -- "${moduleName}" || return "${?}"
}

export PKG_CONFIG_PATH="${buildRoot}"
pkgConfig --exists || semanticError "module not found: ${moduleName}"

if [ "${#variableNames[*]}" -eq 0 ]
then
   pkgConfig --print-variables | sort
else
   for variableName in "${variableNames[@]}"
   do
      pkgConfig --variable="${variableName}"
   done
fi

exit 0
