#!/usr/bin/env bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2026 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/../brltty-prologue.sh"

showProgramUsagePurpose() {
cat <<END_OF_PROGRAM_USAGE_PURPOSE
Convert a document from reStructured text to plain text.
END_OF_PROGRAM_USAGE_PURPOSE
}

showProgramUsageNotes() {
cat <<END_OF_PROGRAM_USAGE_NOTES
If the input file is specified as a minus sign (-) then the reStructured text is read from standard input.
Likewise, if the output file is specified as a minus sign (-) then the plain text is written to standard output.
END_OF_PROGRAM_USAGE_NOTES
}

addProgramParameter input rstFile "an existing document formatted as reStructured text"
addProgramParameter output textFile "where to write the plain text document"
parseProgramArguments "${@}"

[ "${rstFile}" = "-" ] || verifyInputFile "${rstFile}"

pandocOptions=(--from html --to plain)
pandocOptions+=(--lua-filter "${programPath}.lua")

[ "${textFile}" = "-" ] || {
   verifyOutputFile "${textFile}"
   pandocOptions+=(--output "${textFile}")
}

needTemporaryDirectory
htmlFile="${temporaryDirectory}/document.html"

set -e
cd "${initialDirectory}"
rst2html --config "${programDirectory}/docutils.conf" -- "${rstFile}" "${htmlFile}"

pandoc "${pandocOptions[@]}" -- "${htmlFile}"
exit 0
