#!/usr/bin/env tclsh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2026 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

source [file join [file dirname [info script]] .. brltty-prologue.tcl]

set serialProperties [dict create]

proc getSerialPropertyNames {} {
   global serialProperties
   return [dict keys $serialProperties]
}

proc isSerialPropertyDefined {name} {
   return [lcontain [getSerialPropertyNames] $name]
}

proc getSerialPropertyLabel {name} {
   global serialProperties
   return [string map {- " "} [dict get $serialProperties $name long]]
}

proc getSerialPropertyChoices {name} {
   global serialProperties
   return [dict get $serialProperties $name choices]
}

proc getSerialPropertyOptions {name} {
   global serialProperties
   return [dict get $serialProperties $name options]
}

proc getSerialPropertySetting {name} {
   global serialProperties
   return [dict get $serialProperties $name setting]
}

proc verifySerialPropertyChoice {name value} {
   if {![lcontain [getSerialPropertyChoices $name] $value]} {
      return -code error "unknown serial [getSerialPropertyLabel $name]: $value"
   }
}

proc setSerialPropertyField {name field value} {
   global serialProperties
   dict set serialProperties $name $field $value
}

proc defineSerialProperty {name short long help default args} {
   if {[isSerialPropertyDefined $name]} {
      return -code error "serial property already defined: $name"
   }

   global serialProperties
   dict set serialProperties $name [dict create short $short long $long help $help choices $args options [dict create]]

   verifySerialPropertyChoice $name $default
   setSerialPropertyField $name setting $default
}

proc addSerialOption {option property args} {
   if {![isSerialPropertyDefined $property]} {
      return -code error "serial property not defined: $property"
   }

   global serialProperties

   foreach value $args {
      verifySerialPropertyChoice $property $value
   }

   dict set serialProperties $property options $option $args
}

defineSerialProperty lineMode m mode "the line mode" local local modem
defineSerialProperty lineBaud b baud "the serial baud" 38400 50 75 110 134 150 200 300 600 1200 1800 2400 4800 9600 19200 38400 57600 115200 230400 460800 500000 576000 921600 1000000 1152000 1500000 2000000 2500000 3000000 3500000 4000000
defineSerialProperty flowControl f flow-control "the flow control" no no hardware software
defineSerialProperty dataParity p parity "the data parity" none none odd even mark space
defineSerialProperty dataBits d data-bits "the number of data bits" 8 5 6 7 8
defineSerialProperty stopBits s stop-bits "the number of stop bits" 1 1 2

addSerialOption clocal lineMode local
addSerialOption crtscts flowControl hardware
addSerialOption ixon flowControl software
addSerialOption parenb dataParity odd even mark space
addSerialOption parodd dataParity odd mark
addSerialOption cmspar dataParity mark space
addSerialOption cstopb stopBits 2

proc logSerialConfiguration {} {
   global devicePath

   set log $devicePath
   set delimiter :

   foreach name [getSerialPropertyNames] {
      append log "$delimiter "
      set delimiter ,

      append log [getSerialPropertyLabel $name]
      append log " [getSerialPropertySetting $name]"
   }

   logTask $log
}

proc verifyDevicePath {path} {
   foreach {test word} {exists "found" readable "readable" writable "writable"} {
      if {![file $test $path]} {
         semanticError "device not $word: $path"
      }
   }

   if {![string equal [file type $path] characterSpecial]} {
      semanticError "not a character special device: $path"
   }
}

proc verifySerialChannel {channel path} {
   array set properties [fconfigure $channel]

   if {![info exists properties(-mode)]} {
      semanticError "not a serial device: $path"
   }
}

proc getConfigurationOptions {} {
   set configuration [list raw -echo -echoe -echok -echonl]
   lappend configuration [getSerialPropertySetting lineBaud]
   lappend configuration cs[getSerialPropertySetting dataBits]

   foreach name [getSerialPropertyNames] {
      set setting [getSerialPropertySetting $name]
      set options [getSerialPropertyOptions $name]

      foreach option [dict keys $options] {
         if {![lcontain [dict get $options $option] $setting]} {
            set option "-$option"
         }

         lappend configuration $option
      }
   }

   return $configuration
}

proc configureSerialDevice {args} {
   set command [list stty]
   lappend command {*}$args
   logDetail "command: [join $command " "]"

   try {
      return [exec <@ $::deviceChannel {*}$command 2>@ stderr]
   } trap {POSIX} {message} {
      logError $message
      exit 11
   } trap {CHILDSTATUS} {} {
      exit 12
   }
}

proc parseScriptArguments {} {
   global serialProperties

   set parser [::brltty::ScriptArgumentsParser new]
   $parser setPurpose "Interactively send data to and view data received from a serial device."

   $parser requiredParameter devicePath device "the path to the serial device"
   $parser flagOption noSession n no-session "don't start the interactive session"

   foreach name [dict keys $serialProperties] {
      set properties [dict get $serialProperties $name]

      set short [dict get $properties short]
      set long [dict get $properties long]
      set help [dict get $properties help]
      set choices [dict get $properties choices]
      set default [dict get $properties setting]

      $parser stringOption $name $short $long choice.$default $help $choices
   }

   $parser addNotes {
      "Each full line read from standard input is sent to the serial device;"
      "its trailing newline (\\n) isn't sent."
      "All TCL-recognized backslash escape sequences are interpreted as documented."
      "Use \\\\, therefore, to send an actual backslash."
      "Use \\x to to specify a byte to be sent via its hexadecimal value."
      "Entering a zero-length line or an end-of-file (usually Control D) ends the interactive session."
      ""
      "All bytes received from the serial device are written to standard output as a two-digit hexadecimal number followed by a space."
   }

   return [$parser parseArguments]
}

set argumentValues [parseScriptArguments]
set noSession [dict get $argumentValues noSession]

foreach name [getSerialPropertyNames] {
   setSerialPropertyField $name setting [dict get $argumentValues $name]
}

if {![string equal [file pathtype [set devicePath [dict get $argumentValues devicePath]]] absolute]} {
   set devicePath [file join [file separator] dev $devicePath]
}

logSerialConfiguration
set configurationOptions [getConfigurationOptions]
logNote "configuration options: [join $configurationOptions " "]"
verifyDevicePath $devicePath

if {!$noSession} {
   withChannel deviceChannel [open $devicePath {RDWR NOCTTY NONBLOCK}] {
      verifySerialChannel $deviceChannel $devicePath
      fconfigure $deviceChannel -buffering none -translation binary

      configureSerialDevice {*}$configurationOptions
      logNotice "interactive session started"

      fileevent $deviceChannel readable {
         foreach byte [split [read $deviceChannel] ""] {
            scan $byte %c number
            puts -nonewline stdout [format "%02x " $number]
         }

         flush stdout
      }

      fileevent stdin readable {
         if {[set length [gets stdin line]] > 0} {
            puts -nonewline $deviceChannel [subst -nocommands -novariables $line]
            flush $deviceChannel
         } elseif {$length == 0} {
            set endReason "zero-length line on standard input"
         } elseif {[eof stdin]} {
            puts stdout ""
            flush stdout
            set endReason "end-of-file on standard input"
         }
      }

      vwait endReason
      logNotice "interactive session ended - $endReason"
   }
}

exit 0
