#!/usr/bin/env tclsh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2026 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

source [file join [file dirname [info script]] .. brltty-prologue.tcl]

set serialProperties [dict create]

proc getSerialPropertyNames {} {
   global serialProperties
   return [dict keys $serialProperties]
}

proc isSerialPropertyDefined {name} {
   return [lcontain [getSerialPropertyNames] $name]
}

proc getSerialPropertyLabel {name} {
   global serialProperties
   return [string map {- " "} [dict get $serialProperties $name long]]
}

proc getSerialPropertyChoices {name} {
   global serialProperties
   return [dict get $serialProperties $name choices]
}

proc getSerialPropertyOptions {name} {
   global serialProperties
   return [dict get $serialProperties $name options]
}

proc getSerialPropertySetting {name} {
   global serialProperties
   return [dict get $serialProperties $name setting]
}

proc verifySerialPropertyChoice {name value} {
   if {![lcontain [getSerialPropertyChoices $name] $value]} {
      return -code error "unknown serial [getSerialPropertyLabel $name]: $value"
   }
}

proc setSerialPropertyField {name field value} {
   global serialProperties
   dict set serialProperties $name $field $value
}

proc defineSerialProperty {name short long help default args} {
   if {[isSerialPropertyDefined $name]} {
      return -code error "serial property already defined: $name"
   }

   global serialProperties
   dict set serialProperties $name [dict create short $short long $long help $help choices $args options [dict create]]

   verifySerialPropertyChoice $name $default
   setSerialPropertyField $name setting $default
}

proc addSerialOption {option property args} {
   if {![isSerialPropertyDefined $property]} {
      return -code error "serial property not defined: $property"
   }

   global serialProperties

   foreach value $args {
      verifySerialPropertyChoice $property $value
   }

   dict set serialProperties $property options $option $args
}

defineSerialProperty lineMode m mode "the line mode" local local modem
defineSerialProperty lineBaud b baud "the serial baud" 38400 50 75 110 134 150 200 300 600 1200 1800 2400 4800 9600 19200 38400 57600 115200 230400 460800 500000 576000 921600 1000000 1152000 1500000 2000000 2500000 3000000 3500000 4000000
defineSerialProperty flowControl f flow-control "the flow control" no no hardware software
defineSerialProperty dataParity p parity "the data parity" none none odd even mark space
defineSerialProperty dataBits d data-bits "the number of data bits" 8 5 6 7 8
defineSerialProperty stopBits s stop-bits "the number of stop bits" 1 1 2

addSerialOption clocal lineMode local
addSerialOption crtscts flowControl hardware
addSerialOption ixon flowControl software
addSerialOption parenb dataParity odd even mark space
addSerialOption parodd dataParity odd mark
addSerialOption cmspar dataParity mark space
addSerialOption cstopb stopBits 2

proc logSerialConfiguration {} {
   global devicePath

   set log $devicePath
   set delimiter :

   foreach name [getSerialPropertyNames] {
      append log "$delimiter "
      set delimiter ,

      append log [getSerialPropertyLabel $name]
      append log " [getSerialPropertySetting $name]"
   }

   logTask $log
}

proc verifySerialDevice {path} {
   foreach {test word} {exists "found" readable "readable" writable "writable"} {
      if {![file $test $path]} {
         semanticError "device not $word: $path"
      }
   }

   if {![string equal [file type $path] characterSpecial]} {
      semanticError "not a serial device: $path"
   }
}

proc configureSerialDevice {args} {
   global devicePath

   set command [list stty -F $devicePath]
   lappend command {*}$args
   logDetail "command: [join $command " "]"

   try {
      return [exec {*}$command 2>@ stderr]
   } trap {CHILDSTATUS} {} {
      exit 9
   } trap {POSIX} {message} {
      logError $message
      exit 8
   }
}

proc getRequestedConfiguration {} {
   set configuration [list raw -echo -echoe -echok -echonl]
   lappend configuration [getSerialPropertySetting lineBaud]
   lappend configuration cs[getSerialPropertySetting dataBits]

   foreach property [getSerialPropertyNames] {
      set setting [getSerialPropertySetting $property]
      set options [getSerialPropertyOptions $property]

      foreach option [dict keys $options] {
         if {![lcontain [dict get $options $option] $setting]} {
            set option "-$option"
         }

         lappend configuration $option
      }
   }

   return $configuration
}

proc parseScriptArguments {} {
   set parser [::brltty::ScriptArgumentsParser new]
   global serialProperties

   foreach name [dict keys $serialProperties] {
      set properties [dict get $serialProperties $name]

      set short [dict get $properties short]
      set long [dict get $properties long]
      set help [dict get $properties help]
      set choices [dict get $properties choices]
      set default [dict get $properties setting]

      $parser stringOption $name $short $long choice.$default $help $choices
   }

   $parser requiredParameter devicePath device "the path to the serial device"

   return [$parser parseArguments]
}

set argumentValues [parseScriptArguments]

foreach name [getSerialPropertyNames] {
   setSerialPropertyField $name setting [dict get $argumentValues $name]
}

if {![string equal [file pathtype [set devicePath [dict get $argumentValues devicePath]]] absolute]} {
   set devicePath [file join / dev $devicePath]
}

verifySerialDevice $devicePath
logSerialConfiguration

set originalConfiguration [configureSerialDevice -g]
set requestedConfiguration [getRequestedConfiguration]
logNote "stty options: [join $requestedConfiguration " "]"

try {
   configureSerialDevice {*}$requestedConfiguration

   try {
      withChannel deviceChannel [open $devicePath {RDWR NOCTTY NONBLOCK}] {
         fconfigure $deviceChannel -buffering none -translation binary

         fileevent $deviceChannel readable {
            foreach byte [split [read $deviceChannel] ""] {
               scan $byte %c number
               puts -nonewline stdout [format "%02x " $number]
            }

            flush stdout
         }

         fileevent stdin readable {
            if {[set length [gets stdin line]] == 0} {
               set exitStatus 0
            } elseif {$length > 0} {
               puts -nonewline $deviceChannel [subst -nocommands -novariables $line]
               flush $deviceChannel
            } elseif {[eof stdin]} {
               set exitStatus 0
            }
         }

         vwait exitStatus
      }
   } trap {POSIX} {problem} {
      semanticError $message
   }
} finally {
   configureSerialDevice $originalConfiguration
}

exit $exitStatus
