#!/usr/bin/env tclsh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2026 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

source [file join [file dirname [info script]] .. prologue.tcl]
source [file join $scriptDirectory csv.tcl]

set optionDefinitions {
   {missing flag "check for missing definitions"}
   {noupdate flag "don't update changed tables"}
}

set defaultInputFile [file join $sourceRoot $documentsSubdirectory brltty.conf.in]
addProgramOption optionDefinitions input string.file "the input file" $defaultInputFile

set defaultOutputDirectory [file join $sourceRoot $documentsSubdirectory]
addProgramOption optionDefinitions output string.directory "the output directory" $defaultOutputDirectory
processProgramArguments optionValues $optionDefinitions

if {![info exists optionValues(input)]} {
   set optionValues(input) $defaultInputFile
}

if {![info exists optionValues(output)]} {
   set optionValues(output) $defaultOutputDirectory
}

verifyInputFile $optionValues(input)
verifyOutputDirectory $optionValues(output)

proc reportProblem {problem} {
   logWarning $problem
}

proc makeLists {} {
   global definitions
   set pattern {^#(\w+)-(driver|table|parameters)\s+([^\s]*?)\s*#\s*(.*?)\s*$}

   forEachLine line $::optionValues(input) {
      if {[regexp -nocase -- $pattern $line x type category operand comment]} {
         set category [string trimright [string tolower $category] s]
         set type [string tolower $type]
         set columns [linsert [lmap column [split $comment ";"] {string trim $column}] 0 $operand]

         if {[checkDefinition $category $type columns]} {
            if {![dict exists $definitions $category $type list]} {
               dict set definitions $category $type list {}
            }

            dict with definitions $category $type {
               lappend list $columns
            }
         }
      }
   }

   if {$::optionValues(missing)} {
      checkForMissingDefinitions
   }
}

proc checkDefinition {category type columnsVariable} {
   global definitions
   upvar 1 $columnsVariable columns

   if {[lsearch -exact [dict getdef $definitions $category $type accept {}] [lindex $columns 0]] >= 0} {
      return 1
   }

   set handler "check[string totitle $category]Definition"
   if {[llength [info procs $handler]] == 0} {
      logError "handler not defined: $handler"

      proc $handler {category type columnsVariable} {
	 return 0
      }
   }

   return [$handler $category $type columns]
}

proc checkDriverDefinition {category type columnsVariable} {
   global definitions
   upvar 1 $columnsVariable columns

   lassign $columns code name
   checkForDuplicateDefinition $category $type $name

   set properties [dict get $definitions $category $type]
   set subdirectory [dict get $properties subdirectory]
   set makeFile [file join $::sourceRoot $subdirectory $name Makefile.in]

   if {[file isfile $makeFile]} {
      if {[getDriverProperty $makeFile DRIVER_CODE driverCode]} {
         if {![string equal $driverCode $code]} {
            reportProblem "inconsistent $type $category code: $driverCode != $code"
         }
      }

      if {[getDriverProperty $makeFile DRIVER_NAME driverName]} {
         if {![string equal $driverName $name]} {
            reportProblem "inconsistent $type $category name: $driverName != $name"
         }
      }

      return 1
   } else {
      reportProblem "unrecognized $type $category name: $name"
   }

   return 0
}

proc checkTableDefinition {category type columnsVariable} {
   global definitions
   upvar 1 $columnsVariable columns

   lassign $columns name
   checkForDuplicateDefinition $category $type $name

   set properties [dict get $definitions $category $type]
   set subdirectory [dict get $properties subdirectory]
   set extension [dict get $properties extension]
   set table [file join $::sourceRoot $subdirectory $name.$extension]

   if {[file isfile $table]} {
      return 1
   } else {
      reportProblem "unrecognized $type $category name: $name"
   }

   return 0
}

proc checkParameterDefinition {category type columnsVariable} {
   global definitions
   upvar 1 $columnsVariable columns

   lassign $columns parameter
   set pattern {^(?:([[:alnum:]]+):)?([_[:alpha:]]+)=(.*)$}

   if {[regexp $pattern $parameter x qualifier name default]} {
      set columns [lreplace $columns 0 0 $qualifier $name $default]
      return 1
   } else {
      reportProblem "unrecognized $type $category: $parameter"
   }

   return 0
}

proc checkForDuplicateDefinition {category type name} {
   global definitions

   if {[dict exists $definitions $category $type names $name]} {
      reportProblem "duplicate $type $category definition: $name"
   } else {
      dict set definitions $category $type names $name [dict create]
   }
}

proc checkForMissingDefinitions {} {
   checkForMissingDriverDefinitions braille
   checkForMissingDriverDefinitions speech
   checkForMissingDriverDefinitions screen

   checkForMissingTableDefinitions text
   checkForMissingTableDefinitions contraction
   checkForMissingTableDefinitions attributes
   checkForMissingTableDefinitions keyboard
}

proc checkForMissingDriverDefinitions {type} {
   global definitions

   set category driver
   set properties [dict get $definitions $category $type]
   set subdirectory [dict get $properties subdirectory]

   foreach name [listSubdirectory $subdirectory *] {
      checkForMissingDefinition $category $type $name
   }
}

proc checkForMissingTableDefinitions {type} {
   global definitions

   set category table
   set properties [dict get $definitions $category $type]
   set subdirectory [dict get $properties subdirectory]
   set extension [dict get $properties extension]

   foreach file [listSubdirectory $subdirectory *.$extension] {
      checkForMissingDefinition $category $type [file rootname $file]
   }
}

proc checkForMissingDefinition {category type name} {
   global definitions

   if {[lsearch -exact [dict getdef $definitions $category $type missing {}] $name] < 0} {
      if {![dict exists $definitions $category $type names $name]} {
         reportProblem "missing $type $category definition: $name"
      }
   }
}

proc listSubdirectory {subdirectory pattern} {
   return [lsort [glob -nocomplain -directory [file join $::sourceRoot $subdirectory] -tail -- $pattern]]
}

proc getDriverProperty {makeFile property valueVariable} {
   upvar 1 $valueVariable value

   if {[file exists $makeFile]} {
      if {[getMakeFileProperty $makeFile $property value]} {
         return 1
      } else {
         reportProblem "missing driver property: $property: $makeFile"
      }
   }

   set value ""
   return 0
}

proc updateTables {} {
   global definitions
   set updated 0

   foreach category [dict keys $definitions] {
      foreach type [dict keys [dict get $definitions $category]] {
         if {[updateTable $category $type]} {
            set updated 1
         }
      }
   }

   if {[updateDriverCodeTable]} {
      set updated 1
   }

   return $updated
}

proc updateTable {category type} {
   global definitions

   set list [dict getdef $definitions $category $type list {}]
   set list [lsort -index 0 $list]

   set headers [dict get $definitions $category $type headers]
   set rows [csvNormalizeRows [linsert $list 0 $headers] [llength $headers]]

   if {[string equal $category driver]} {
      set usageColumn [list usage]
      set driversDirectory [file join $::sourceRoot [dict get $definitions $category $type subdirectory]]

      foreach columns [lrange $rows 1 end] {
         set driverName [lindex $columns 1]
         set makeFile [file join $driversDirectory $driverName Makefile.in]
         getDriverProperty $makeFile DRIVER_USAGE driverUsage
         lappend usageColumn $driverUsage
      }

      set rows [lmap columns $rows usage $usageColumn {
         linsert $columns end $usage
      }]
   } elseif {[string equal $category parameter] && [string equal $type api]} {
      set rows [lmap row $rows {lrange $row 1 end}]
   }

   return [updateFile "$type-$category" [csvMakeTable $rows]]
}

proc updateDriverCodeTable {} {
   global definitions

   set drivers [dict get $definitions driver]
   set types [dict create]

   foreach type [dict keys $drivers] {
      foreach columns [dict getdef $drivers $type list {}] {
         lassign $columns code name

         if {![dict exists $types $code $name]} {
            dict set types $code $name list {}
         }
 
         dict with types $code $name {
            lappend list $type
         }
      }
   }

   set headers {code name types}
   set rows [list $headers]

   foreach code [lsort [dict keys $types]] {
      set codeEntry [dict get $types $code]
      set names [lsort [dict keys $codeEntry]]

      if {[dict size $codeEntry] > 1} {
         reportProblem "ambiguous driver code: $code ([join $names ", "])"
      }

      foreach name $names {
         set row [list $code $name]

         dict with codeEntry $name {
            lappend row [join $list ", "]
         }

         lappend rows $row
      }
   }

   return [updateFile "driver-code" [csvMakeTable $rows]]
}

proc updateFile {name data} {
   set file "[file join $::optionValues(output) $name].csv"

   if {!$::optionValues(noupdate)} {
      return [replaceFile $file $data]
   }

   if {![file exists $file]} {
      logDetail "file not added: $file"
   } elseif {[string equal [readFile $file] $data]} {
      logDetail "file not changed: $file"
   } else {
      logDetail "file not updated: $file"
   }

   return 0
}

proc makeDefinitions {} {
   set tableHeaders {name description}
   set parameterHeaders {qualifier name example comment}
   set driverParameterHeaders [lreplace $parameterHeaders 0 0 driver]
   set privilegeParameterHeaders [lreplace $parameterHeaders 0 0 platform]

   set definitions [makeDictionary {
      driver dict {
         braille dict {
            headers list {code name aliases others}
            subdirectory subst $::brailleDriversSubdirectory
            accept list {auto}
            missing list {Skeleton TTY XWindow B2G}
         }

         speech dict {
            headers list {code name aliases}
            subdirectory subst $::speechDriversSubdirectory
            accept list {auto}
            missing list {Skeleton}
         }

         screen dict {
            headers list {code name}
            subdirectory subst $::screenDriversSubdirectory
            missing list {Skeleton Grub}
         }
      }

      table dict {
         text dict {
            headers subst $tableHeaders
            subdirectory subst $::textTablesSubdirectory
            extension subst $::textTableExtension
            accept list {auto}
         }

         contraction dict {
            headers subst $tableHeaders
            subdirectory subst $::contractionTablesSubdirectory
            extension subst $::contractionTableExtension
            accept list {auto}
            missing list {none}
         }

         attributes dict {
            headers subst $tableHeaders
            subdirectory subst $::attributesTablesSubdirectory
            extension subst $::attributesTableExtension
         }

         keyboard dict {
            headers subst $tableHeaders
            subdirectory subst $::keyboardTablesSubdirectory
            extension subst $::keyTableExtension
            accept list {off}
         }
      }

      parameter dict {
         braille dict {
            headers subst $driverParameterHeaders
         }

         speech dict {
            headers subst $driverParameterHeaders
         }

         screen dict {
            headers subst $driverParameterHeaders
         }

         api dict {
            headers subst $parameterHeaders
         }

         privilege dict {
            headers subst $privilegeParameterHeaders
         }
      }
   }]

   return $definitions
}

set definitions [makeDefinitions]
makeLists

if {![updateTables]} {
   logTask "no files updated"
}

exit 0
