#!/bin/bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2023 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "`dirname "${0}"`/../prologue.sh"
parseProgramArguments "${@}"

setSourceRoot
set -e

cd "${sourceRoot}/${programsSubdirectory}"
make --silent brltty-lscmds
newText="$(./brltty-lscmds)"

cd "${sourceRoot}/${documentsSubdirectory}"
outputFile="README.CommandReference"

if [ -e "${outputFile}" ]
then
   [ -f "${outputFile}" ] || semanticError "not a file: ${outputFile}"
   [ -r "${outputFile}" ] || semanticError "file not readable: ${outputFile}"
   oldText="$(cat "${outputFile}")"

   if [ "${oldText}" = "${newText}" ]
   then
      logTask "not updated"
      exit 0
   fi

   [ -w "${outputFile}" ] || semanticError "file not writable: ${outputFile}"
   fileVerb="updating"
else
   fileVerb="adding"
fi

logNotice "${fileVerb} file: ${outputFile}"
echo "${newText}" >"${outputFile}"
exit 0
