#!/bin/bash
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2023 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU Lesser General Public License, as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any
# later version. Please see the file LICENSE-LGPL for details.
#
# Web Page: http://brltty.app/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

. "$(dirname "${0}")/../prologue.sh"
setSourceRoot
cd $sourceRoot

addProgramOption c flag updateCommandReference "update the command reference"
addProgramOption s flag updateAndroidSettings "update the Android settings resources"
addProgramOption t flag updateCSVTables "update the CSV tables"
addProgramOption u flag updateUSBDevices "update the USB device lists"
parseProgramArguments "${@}"

updateAll=true
set -- updateAndroidSettings updateCommandReference updateCSVTables updateUSBDevices

for variable
do
   "${!variable}" && updateAll=false
done

"${updateAll}" && {
   for variable
   do
      setVariable "${variable}" true
   done
}

"${updateAndroidSettings}" && Android/Tools/mksettings
"${updateCommandReference}" && Tools/updcmdref
"${updateCSVTables}" && Tools/updcsvs
"${updateUSBDevices}" && Tools/updusbdevs

exit 0
