#!/bin/bash -p
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2014 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any
# later version. Please see the file LICENSE-GPL for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

set -e
shopt -s nullglob

defaultArchiveName="brltty-dos"
defaultInstallDirectory="BRLTTY"

. "`dirname "${0}"`/../prologue.sh"
addProgramOption a string.name archiveName "specify archive name (default is ${defaultArchiveName})"
addProgramOption i string.directory installDirectory "specify installation directory on target system (default is ${defaultInstallDirectory})"
addProgramOption n flag reportShortNameCollisions "report short name conflicts"
addProgramOption o flag overwriteArchive "overwrite existing archive"
addProgramOption s flag invokeShell "invoke interactive shell to inspect/modify result"
addProgramParameter source sourceDirectory "top-level directory of source tree"
eval "${parseProgramOptions}"

[ -n "${archiveName}" ] || archiveName="${defaultArchiveName}"
[ -n "${installDirectory}" ] || installDirectory="${defaultInstallDirectory}"

[ -n "${sourceDirectory}" ] || sourceDirectory="."
verifyInputDirectory "${sourceDirectory}" || semanticError
sourceDirectory="$(resolveDirectory "${sourceDirectory}")"

archivePath="${initialDirectory}/${archiveName}.zip"
[ ! -e "${archivePath}" ] || {
   "${overwriteArchive}" ] || semanticError "archive already exists: ${archivePath}"
   rm -f -r "${archivePath}"
}

function convertTextFile {
   local file="${1}"

   unix2dos -q -o "${file}"
}

function installTextFile {
   local sourceFile="${1}"
   local targetFile="${2}"

   targetFile="${installDirectory}/${targetFile}"
   local targetDirectory="${targetFile%/*}"
   mkdir -p "${targetDirectory}"
   cp "${sourceFile}" "${targetFile}"
   convertTextFile "${targetFile}"
}

function installBinaryFile {
   local sourceFile="${1}"
   local targetFile="${2}"

   targetFile="${installDirectory}/${targetFile}"
   local targetDirectory="${targetFile%/*}"
   mkdir -p "${targetDirectory}"
   cp "${sourceFile}" "${targetFile}"
}

function installManualFiles {
   local directory="${1}"

   cd "${directory}/Documents/Manual-BRLTTY"

   for file in $(find . -type f)
   do
      case "${file##*/}"
      in
         *.txt | *.htm | *.html)
            installTextFile "${file}" "${manualSubdirectory}/${file}"
            ;;

         *.doc | *.pdf)
            installBinaryFile "${file}" "${manualSubdirectory}/${file}"
            ;;
      esac
   done
}

needTemporaryDirectory

buildDirectory="${temporaryDirectory}/build"
mkdir -p "${buildDirectory}"

installDirectory="${temporaryDirectory}/intall/${installDirectory}"
mkdir -p "${installDirectory}"
documentSubdirectory="doc"
manualSubdirectory="${documentSubdirectory}/Manual"

cd "${buildDirectory}"
"${sourceDirectory}/cfg-dos" --enable-relocatable-install --prefix="${installDirectory}"
make -s all
make -s -C Programs ktbtest.exe tunetest.exe
make -s -C Documents
make -s install

cd "${installDirectory}/bin"
rm brltty-config
rm brltty-install
mv brltty-ttb.exe brlttb.exe
mv brltty-ctb.exe brlctb.exe
mv brltty-trtxt.exe brltrtxt.exe

cd "${buildDirectory}/Programs"
installBinaryFile ktbtest.exe bin/brlktb.exe
installBinaryFile tunetest.exe bin/brltune.exe

cd "${sourceDirectory}/DOS"
installBinaryFile cwsdpmi.exe "bin/cwsdpmi.exe"

cd "${sourceDirectory}/Drivers"
name=README
for driverType in Braille Speech
do
   cd "${driverType}"

   for driverName in *
   do
      cd "${driverName}"
      typeset -u driverCode="$(sed -n -e '/^ *DRIVER_CODE *= */s/^.*= *//p' "Makefile.in")"

      for file in "${name}"*
      do
         document="${file/#${name}/${driverCode}}"
         document="${document//./-}"
         installTextFile "${file}" "${documentSubdirectory}/Drivers/${driverType}/${document}.txt"
      done

      cd ..
   done

   cd ..
done

cd "${sourceDirectory}"
installTextFile "LICENSE-GPL" "LIC-GPL.txt"
installTextFile "LICENSE-LGPL" "LIC-LGPL.txt"
installTextFile "README" "README.txt"
installTextFile "Documents/README.MSDOS" "MSDOS.txt"
installTextFile "Documents/ChangeLog" "${documentSubdirectory}/CHANGES.txt"
installTextFile "Documents/HISTORY" "${documentSubdirectory}/HISTORY.txt"
installTextFile "Documents/TODO" "${documentSubdirectory}/TODO.txt"

installManualFiles "${sourceDirectory}"
installManualFiles "${buildDirectory}"

cd "${buildDirectory}"
installTextFile "Documents/brltty.conf" "etc/brltty.cfg"

cd "${installDirectory}"
mv share/man .
rm -f -r share
cd man

for source in */*
do
   target="${source/%?/txt}"
   MANWIDTH=80 LC_ALL=C man "${source}" | ul -t dumb | expand | uniq >"${target}"
   rm "${source}"
   convertTextFile "${target}"
done

cd "${installDirectory}/etc/brltty"
for file in *.[tack]t[bi]
do
   convertTextFile "${file}"
done

! "${invokeShell}" || {
   cd "${installDirectory}"
   "${SHELL:-/bin/sh}" || :
}

! "${reportShortNameCollisions}" || {
   cd "${installDirectory}"
   find . -type d -print |
      while read directory
      do
         declare -A shortNames=()

         for longName in $(ls -1 --quote-name --quoting-style=shell "${directory}")
         do
            delimiter="."
            prefix="${longName%${delimiter}*}"

            if [ "${prefix}" = "${longName}" ]
            then
               suffix=""
               delimiter=""
            else
               suffix="${longName:${#prefix}+${#delimiter}}"
            fi

            prefix="${prefix:0:8}"
            suffix="${suffix:0:3}"
            declare -l shortName="${prefix}${delimiter}${suffix}"

            if [ "${#shortNames["${shortName}"]}" -eq 0 ]
            then
               shortNames["${shortName}"]="${longName}"
            else
               programMessage "short name collision: ${directory#.}: ${shortNames["${shortName}"]} & ${longName}"
            fi
         done
      done
}

cd "${installDirectory}/.."
zip -q -r "${archivePath}" "${installDirectory##*/}"
exit 0
