/*
 * BRLTTY - A background process providing access to the console screen (when in
 *          text mode) for a blind person using a refreshable braille display.
 *
 * Copyright (C) 1995-2013 by The BRLTTY Developers.
 *
 * BRLTTY comes with ABSOLUTELY NO WARRANTY.
 *
 * This is free software, placed under the terms of the
 * GNU General Public License, as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any
 * later version. Please see the file LICENSE-GPL for details.
 *
 * Web Page: http://mielke.cc/brltty/
 *
 * This software is maintained by Dave Mielke <dave@mielke.cc>.
 */

#include "prologue.h"

#include <android/keycodes.h>

#include "sys_android.h"

#include "kbd.h"
#include "kbd_internal.h"
#include "kbd_android.h"

const unsigned char keyCodeMap[] = {
  [ANDROID_KEY_0] = KBD_KEY_SYMBOL_Zero_RightParenthesis,
  [ANDROID_KEY_1] = KBD_KEY_SYMBOL_One_Exclamation,
  [ANDROID_KEY_2] = KBD_KEY_SYMBOL_Two_At,
  [ANDROID_KEY_3] = KBD_KEY_SYMBOL_Three_Number,
  [ANDROID_KEY_3D_MODE] = 0,
  [ANDROID_KEY_4] = KBD_KEY_SYMBOL_Four_Dollar,
  [ANDROID_KEY_5] = KBD_KEY_SYMBOL_Five_Percent,
  [ANDROID_KEY_6] = KBD_KEY_SYMBOL_Six_Circumflex,
  [ANDROID_KEY_7] = KBD_KEY_SYMBOL_Seven_Ampersand,
  [ANDROID_KEY_8] = KBD_KEY_SYMBOL_Eight_Asterisk,
  [ANDROID_KEY_9] = KBD_KEY_SYMBOL_Nine_LeftParenthesis,

  [ANDROID_KEY_A] = KBD_KEY_LETTER_A,
  [ANDROID_KEY_ALT_LEFT] = 0,
  [ANDROID_KEY_ALT_RIGHT] = 0,
  [ANDROID_KEY_APOSTROPHE] = 0,
  [ANDROID_KEY_APP_SWITCH] = 0,
  [ANDROID_KEY_ASSIST] = 0,
  [ANDROID_KEY_AT] = 0,
  [ANDROID_KEY_AVR_INPUT] = 0,
  [ANDROID_KEY_AVR_POWER] = 0,

  [ANDROID_KEY_B] = KBD_KEY_LETTER_B,
  [ANDROID_KEY_BACK] = 0,
  [ANDROID_KEY_BACKSLASH] = 0,
  [ANDROID_KEY_BOOKMARK] = 0,
  [ANDROID_KEY_BREAK] = 0,
  [ANDROID_KEY_BUTTON_1] = 0,
  [ANDROID_KEY_BUTTON_10] = 0,
  [ANDROID_KEY_BUTTON_11] = 0,
  [ANDROID_KEY_BUTTON_12] = 0,
  [ANDROID_KEY_BUTTON_13] = 0,
  [ANDROID_KEY_BUTTON_14] = 0,
  [ANDROID_KEY_BUTTON_15] = 0,
  [ANDROID_KEY_BUTTON_16] = 0,
  [ANDROID_KEY_BUTTON_2] = 0,
  [ANDROID_KEY_BUTTON_3] = 0,
  [ANDROID_KEY_BUTTON_4] = 0,
  [ANDROID_KEY_BUTTON_5] = 0,
  [ANDROID_KEY_BUTTON_6] = 0,
  [ANDROID_KEY_BUTTON_7] = 0,
  [ANDROID_KEY_BUTTON_8] = 0,
  [ANDROID_KEY_BUTTON_9] = 0,
  [ANDROID_KEY_BUTTON_A] = 0,
  [ANDROID_KEY_BUTTON_B] = 0,
  [ANDROID_KEY_BUTTON_C] = 0,
  [ANDROID_KEY_BUTTON_L1] = 0,
  [ANDROID_KEY_BUTTON_L2] = 0,
  [ANDROID_KEY_BUTTON_MODE] = 0,
  [ANDROID_KEY_BUTTON_R1] = 0,
  [ANDROID_KEY_BUTTON_R2] = 0,
  [ANDROID_KEY_BUTTON_SELECT] = 0,
  [ANDROID_KEY_BUTTON_START] = 0,
  [ANDROID_KEY_BUTTON_THUMBL] = 0,
  [ANDROID_KEY_BUTTON_THUMBR] = 0,
  [ANDROID_KEY_BUTTON_X] = 0,
  [ANDROID_KEY_BUTTON_Y] = 0,
  [ANDROID_KEY_BUTTON_Z] = 0,

  [ANDROID_KEY_C] = KBD_KEY_LETTER_C,
  [ANDROID_KEY_CALCULATOR] = 0,
  [ANDROID_KEY_CALENDAR] = 0,
  [ANDROID_KEY_CALL] = 0,
  [ANDROID_KEY_CAMERA] = 0,
  [ANDROID_KEY_CAPS_LOCK] = 0,
  [ANDROID_KEY_CAPTIONS] = 0,
  [ANDROID_KEY_CHANNEL_DOWN] = 0,
  [ANDROID_KEY_CHANNEL_UP] = 0,
  [ANDROID_KEY_CLEAR] = 0,
  [ANDROID_KEY_COMMA] = 0,
  [ANDROID_KEY_CONTACTS] = 0,
  [ANDROID_KEY_CTRL_LEFT] = 0,
  [ANDROID_KEY_CTRL_RIGHT] = 0,

  [ANDROID_KEY_D] = KBD_KEY_LETTER_D,
  [ANDROID_KEY_DEL] = 0,
  [ANDROID_KEY_DPAD_CENTER] = 0,
  [ANDROID_KEY_DPAD_DOWN] = 0,
  [ANDROID_KEY_DPAD_LEFT] = 0,
  [ANDROID_KEY_DPAD_RIGHT] = 0,
  [ANDROID_KEY_DPAD_UP] = 0,
  [ANDROID_KEY_DVR] = 0,

  [ANDROID_KEY_E] = KBD_KEY_LETTER_E,
  [ANDROID_KEY_EISU] = 0,
  [ANDROID_KEY_ENDCALL] = 0,
  [ANDROID_KEY_ENTER] = 0,
  [ANDROID_KEY_ENVELOPE] = 0,
  [ANDROID_KEY_EQUALS] = 0,
  [ANDROID_KEY_ESCAPE] = 0,
  [ANDROID_KEY_EXPLORER] = 0,

  [ANDROID_KEY_F] = KBD_KEY_LETTER_F,
  [ANDROID_KEY_F1] = 0,
  [ANDROID_KEY_F10] = 0,
  [ANDROID_KEY_F11] = 0,
  [ANDROID_KEY_F12] = 0,
  [ANDROID_KEY_F2] = 0,
  [ANDROID_KEY_F3] = 0,
  [ANDROID_KEY_F4] = 0,
  [ANDROID_KEY_F5] = 0,
  [ANDROID_KEY_F6] = 0,
  [ANDROID_KEY_F7] = 0,
  [ANDROID_KEY_F8] = 0,
  [ANDROID_KEY_F9] = 0,
  [ANDROID_KEY_FOCUS] = 0,
  [ANDROID_KEY_FORWARD] = 0,
  [ANDROID_KEY_FORWARD_DEL] = 0,
  [ANDROID_KEY_FUNCTION] = 0,

  [ANDROID_KEY_G] = KBD_KEY_LETTER_G,
  [ANDROID_KEY_GRAVE] = 0,
  [ANDROID_KEY_GUIDE] = 0,

  [ANDROID_KEY_H] = KBD_KEY_LETTER_H,
  [ANDROID_KEY_HEADSETHOOK] = 0,
  [ANDROID_KEY_HENKAN] = 0,
  [ANDROID_KEY_HOME] = 0,

  [ANDROID_KEY_I] = KBD_KEY_LETTER_I,
  [ANDROID_KEY_INFO] = 0,
  [ANDROID_KEY_INSERT] = 0,

  [ANDROID_KEY_J] = KBD_KEY_LETTER_J,

  [ANDROID_KEY_K] = KBD_KEY_LETTER_K,
  [ANDROID_KEY_KANA] = 0,
  [ANDROID_KEY_KATAKANA_HIRAGANA] = 0,

  [ANDROID_KEY_L] = KBD_KEY_LETTER_L,
  [ANDROID_KEY_LANGUAGE_SWITCH] = 0,
  [ANDROID_KEY_LEFT_BRACKET] = 0,

  [ANDROID_KEY_M] = KBD_KEY_LETTER_M,
  [ANDROID_KEY_MANNER_MODE] = 0,
  [ANDROID_KEY_MEDIA_CLOSE] = 0,
  [ANDROID_KEY_MEDIA_EJECT] = 0,
  [ANDROID_KEY_MEDIA_FAST_FORWARD] = 0,
  [ANDROID_KEY_MEDIA_NEXT] = 0,
  [ANDROID_KEY_MEDIA_PAUSE] = 0,
  [ANDROID_KEY_MEDIA_PLAY] = 0,
  [ANDROID_KEY_MEDIA_PLAY_PAUSE] = 0,
  [ANDROID_KEY_MEDIA_PREVIOUS] = 0,
  [ANDROID_KEY_MEDIA_RECORD] = 0,
  [ANDROID_KEY_MEDIA_REWIND] = 0,
  [ANDROID_KEY_MEDIA_STOP] = 0,
  [ANDROID_KEY_MENU] = 0,
  [ANDROID_KEY_META_LEFT] = 0,
  [ANDROID_KEY_META_RIGHT] = 0,
  [ANDROID_KEY_MINUS] = 0,
  [ANDROID_KEY_MOVE_END] = 0,
  [ANDROID_KEY_MOVE_HOME] = 0,
  [ANDROID_KEY_MUHENKAN] = 0,
  [ANDROID_KEY_MUSIC] = 0,
  [ANDROID_KEY_MUTE] = 0,

  [ANDROID_KEY_N] = KBD_KEY_LETTER_N,
  [ANDROID_KEY_NOTIFICATION] = 0,
  [ANDROID_KEY_NUM] = 0,
  [ANDROID_KEY_NUMPAD_0] = 0,
  [ANDROID_KEY_NUMPAD_1] = 0,
  [ANDROID_KEY_NUMPAD_2] = 0,
  [ANDROID_KEY_NUMPAD_3] = 0,
  [ANDROID_KEY_NUMPAD_4] = 0,
  [ANDROID_KEY_NUMPAD_5] = 0,
  [ANDROID_KEY_NUMPAD_6] = 0,
  [ANDROID_KEY_NUMPAD_7] = 0,
  [ANDROID_KEY_NUMPAD_8] = 0,
  [ANDROID_KEY_NUMPAD_9] = 0,
  [ANDROID_KEY_NUMPAD_ADD] = 0,
  [ANDROID_KEY_NUMPAD_COMMA] = 0,
  [ANDROID_KEY_NUMPAD_DIVIDE] = 0,
  [ANDROID_KEY_NUMPAD_DOT] = 0,
  [ANDROID_KEY_NUMPAD_ENTER] = 0,
  [ANDROID_KEY_NUMPAD_EQUALS] = 0,
  [ANDROID_KEY_NUMPAD_LEFT_PAREN] = 0,
  [ANDROID_KEY_NUMPAD_MULTIPLY] = 0,
  [ANDROID_KEY_NUMPAD_RIGHT_PAREN] = 0,
  [ANDROID_KEY_NUMPAD_SUBTRACT] = 0,
  [ANDROID_KEY_NUM_LOCK] = 0,

  [ANDROID_KEY_O] = KBD_KEY_LETTER_O,

  [ANDROID_KEY_P] = KBD_KEY_LETTER_P,
  [ANDROID_KEY_PAGE_DOWN] = 0,
  [ANDROID_KEY_PAGE_UP] = 0,
  [ANDROID_KEY_PERIOD] = 0,
  [ANDROID_KEY_PICTSYMBOLS] = 0,
  [ANDROID_KEY_PLUS] = 0,
  [ANDROID_KEY_POUND] = 0,
  [ANDROID_KEY_POWER] = 0,
  [ANDROID_KEY_PROG_BLUE] = 0,
  [ANDROID_KEY_PROG_GREEN] = 0,
  [ANDROID_KEY_PROG_RED] = 0,
  [ANDROID_KEY_PROG_YELLOW] = 0,

  [ANDROID_KEY_Q] = KBD_KEY_LETTER_Q,

  [ANDROID_KEY_R] = KBD_KEY_LETTER_R,
  [ANDROID_KEY_RIGHT_BRACKET] = 0,
  [ANDROID_KEY_RO] = 0,

  [ANDROID_KEY_S] = KBD_KEY_LETTER_S,
  [ANDROID_KEY_SCROLL_LOCK] = 0,
  [ANDROID_KEY_SEARCH] = 0,
  [ANDROID_KEY_SEMICOLON] = 0,
  [ANDROID_KEY_SETTINGS] = 0,
  [ANDROID_KEY_SHIFT_LEFT] = 0,
  [ANDROID_KEY_SHIFT_RIGHT] = 0,
  [ANDROID_KEY_SLASH] = 0,
  [ANDROID_KEY_SOFT_LEFT] = 0,
  [ANDROID_KEY_SOFT_RIGHT] = 0,
  [ANDROID_KEY_SPACE] = 0,
  [ANDROID_KEY_STAR] = 0,
  [ANDROID_KEY_STB_INPUT] = 0,
  [ANDROID_KEY_STB_POWER] = 0,
  [ANDROID_KEY_SWITCH_CHARSET] = 0,
  [ANDROID_KEY_SYM] = 0,
  [ANDROID_KEY_SYSRQ] = 0,

  [ANDROID_KEY_T] = KBD_KEY_LETTER_T,
  [ANDROID_KEY_TAB] = 0,
  [ANDROID_KEY_TV] = 0,
  [ANDROID_KEY_TV_INPUT] = 0,
  [ANDROID_KEY_TV_POWER] = 0,

  [ANDROID_KEY_U] = KBD_KEY_LETTER_U,
  [ANDROID_KEY_UNKNOWN] = 0,

  [ANDROID_KEY_V] = KBD_KEY_LETTER_V,
  [ANDROID_KEY_VOLUME_DOWN] = 0,
  [ANDROID_KEY_VOLUME_MUTE] = 0,
  [ANDROID_KEY_VOLUME_UP] = 0,

  [ANDROID_KEY_W] = KBD_KEY_LETTER_W,
  [ANDROID_KEY_WINDOW] = 0,

  [ANDROID_KEY_X] = KBD_KEY_LETTER_X,

  [ANDROID_KEY_Y] = KBD_KEY_LETTER_Y,
  [ANDROID_KEY_YEN] = 0,

  [ANDROID_KEY_Z] = KBD_KEY_LETTER_Z,
  [ANDROID_KEY_ZENKAKU_HANKAKU] = 0,
  [ANDROID_KEY_ZOOM_IN] = 0,
  [ANDROID_KEY_ZOOM_OUT] = 0,
};
const int keyCodeLimit = ARRAY_COUNT(keyCodeMap);

int
writeKeyboardEvent (int code, int press) {
  return 0;
}

int
monitorKeyboards (KeyboardCommonData *kcd) {
  return 0;
}
