/*
 * BRLTTY - A background process providing access to the console screen (when in
 *          text mode) for a blind person using a refreshable braille display.
 *
 * Copyright (C) 1995-2013 by The BRLTTY Developers.
 *
 * BRLTTY comes with ABSOLUTELY NO WARRANTY.
 *
 * This is free software, placed under the terms of the
 * GNU General Public License, as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any
 * later version. Please see the file LICENSE-GPL for details.
 *
 * Web Page: http://mielke.cc/brltty/
 *
 * This software is maintained by Dave Mielke <dave@mielke.cc>.
 */

#include "prologue.h"

#include "ktb_keyboard.h"

BEGIN_KEY_NAME_TABLE(keyboard)
  KBD_NAME_ENTRY(LETTER, A, "A"),
  KBD_NAME_ENTRY(LETTER, A, "LETTER_A"),

  KBD_NAME_ENTRY(LETTER, B, "B"),
  KBD_NAME_ENTRY(LETTER, B, "LETTER_B"),

  KBD_NAME_ENTRY(LETTER, C, "C"),
  KBD_NAME_ENTRY(LETTER, C, "LETTER_C"),

  KBD_NAME_ENTRY(LETTER, D, "D"),
  KBD_NAME_ENTRY(LETTER, D, "LETTER_D"),

  KBD_NAME_ENTRY(LETTER, E, "E"),
  KBD_NAME_ENTRY(LETTER, E, "LETTER_E"),

  KBD_NAME_ENTRY(LETTER, F, "F"),
  KBD_NAME_ENTRY(LETTER, F, "LETTER_F"),

  KBD_NAME_ENTRY(LETTER, G, "G"),
  KBD_NAME_ENTRY(LETTER, G, "LETTER_G"),

  KBD_NAME_ENTRY(LETTER, H, "H"),
  KBD_NAME_ENTRY(LETTER, H, "LETTER_H"),

  KBD_NAME_ENTRY(LETTER, I, "I"),
  KBD_NAME_ENTRY(LETTER, I, "LETTER_I"),

  KBD_NAME_ENTRY(LETTER, J, "J"),
  KBD_NAME_ENTRY(LETTER, J, "LETTER_J"),

  KBD_NAME_ENTRY(LETTER, K, "K"),
  KBD_NAME_ENTRY(LETTER, K, "LETTER_K"),

  KBD_NAME_ENTRY(LETTER, L, "L"),
  KBD_NAME_ENTRY(LETTER, L, "LETTER_L"),

  KBD_NAME_ENTRY(LETTER, M, "M"),
  KBD_NAME_ENTRY(LETTER, M, "LETTER_M"),

  KBD_NAME_ENTRY(LETTER, N, "N"),
  KBD_NAME_ENTRY(LETTER, N, "LETTER_N"),

  KBD_NAME_ENTRY(LETTER, O, "O"),
  KBD_NAME_ENTRY(LETTER, O, "LETTER_O"),

  KBD_NAME_ENTRY(LETTER, P, "P"),
  KBD_NAME_ENTRY(LETTER, P, "LETTER_P"),

  KBD_NAME_ENTRY(LETTER, Q, "Q"),
  KBD_NAME_ENTRY(LETTER, Q, "LETTER_Q"),

  KBD_NAME_ENTRY(LETTER, R, "R"),
  KBD_NAME_ENTRY(LETTER, R, "LETTER_R"),

  KBD_NAME_ENTRY(LETTER, S, "S"),
  KBD_NAME_ENTRY(LETTER, S, "LETTER_S"),

  KBD_NAME_ENTRY(LETTER, T, "T"),
  KBD_NAME_ENTRY(LETTER, T, "LETTER_T"),

  KBD_NAME_ENTRY(LETTER, U, "U"),
  KBD_NAME_ENTRY(LETTER, U, "LETTER_U"),

  KBD_NAME_ENTRY(LETTER, V, "V"),
  KBD_NAME_ENTRY(LETTER, V, "LETTER_V"),

  KBD_NAME_ENTRY(LETTER, W, "W"),
  KBD_NAME_ENTRY(LETTER, W, "LETTER_W"),

  KBD_NAME_ENTRY(LETTER, X, "X"),
  KBD_NAME_ENTRY(LETTER, X, "LETTER_X"),

  KBD_NAME_ENTRY(LETTER, Y, "Y"),
  KBD_NAME_ENTRY(LETTER, Y, "LETTER_Y"),

  KBD_NAME_ENTRY(LETTER, Z, "Z"),
  KBD_NAME_ENTRY(LETTER, Z, "LETTER_Z"),

  KBD_NAME_ENTRY(DIGIT, Zero, "Zero"),
  KBD_NAME_ENTRY(DIGIT, Zero, "DIGIT_Zero"),

  KBD_NAME_ENTRY(DIGIT, One, "One"),
  KBD_NAME_ENTRY(DIGIT, One, "DIGIT_One"),

  KBD_NAME_ENTRY(DIGIT, Two, "Two"),
  KBD_NAME_ENTRY(DIGIT, Two, "DIGIT_Two"),

  KBD_NAME_ENTRY(DIGIT, Three, "Three"),
  KBD_NAME_ENTRY(DIGIT, Three, "DIGIT_Three"),

  KBD_NAME_ENTRY(DIGIT, Four, "Four"),
  KBD_NAME_ENTRY(DIGIT, Four, "DIGIT_Four"),

  KBD_NAME_ENTRY(DIGIT, Five, "Five"),
  KBD_NAME_ENTRY(DIGIT, Five, "DIGIT_Five"),

  KBD_NAME_ENTRY(DIGIT, Six, "Six"),
  KBD_NAME_ENTRY(DIGIT, Six, "DIGIT_Six"),

  KBD_NAME_ENTRY(DIGIT, Seven, "Seven"),
  KBD_NAME_ENTRY(DIGIT, Seven, "DIGIT_Seven"),

  KBD_NAME_ENTRY(DIGIT, Eight, "Eight"),
  KBD_NAME_ENTRY(DIGIT, Eight, "DIGIT_Eight"),

  KBD_NAME_ENTRY(DIGIT, Nine, "Nine"),
  KBD_NAME_ENTRY(DIGIT, Nine, "DIGIT_Nine"),

  KBD_NAME_ENTRY(SYMBOL, Grave_Tilde, "Grave"),
  KBD_NAME_ENTRY(SYMBOL, Grave_Tilde, "SYMBOL_Grave_Tilde"),

  KBD_NAME_ENTRY(SYMBOL, Backslash_Bar, "Backslash"),
  KBD_NAME_ENTRY(SYMBOL, Backslash_Bar, "SYMBOL_Backslash_Bar"),

  KBD_NAME_ENTRY(SYMBOL, Minus_Underscore, "Minus"),
  KBD_NAME_ENTRY(SYMBOL, Minus_Underscore, "SYMBOL_Minus_Underscore"),

  KBD_NAME_ENTRY(SYMBOL, Equals_Plus, "Equals"),
  KBD_NAME_ENTRY(SYMBOL, Equals_Plus, "SYMBOL_Equals_Plus"),

  KBD_NAME_ENTRY(SYMBOL, LeftBracket_LeftBrace, "LeftBracket"),
  KBD_NAME_ENTRY(SYMBOL, LeftBracket_LeftBrace, "SYMBOL_LeftBracket_LeftBrace"),

  KBD_NAME_ENTRY(SYMBOL, RightBracket_RightBrace, "RightBracket"),
  KBD_NAME_ENTRY(SYMBOL, RightBracket_RightBrace, "SYMBOL_RightBracket_RightBrace"),

  KBD_NAME_ENTRY(SYMBOL, Semicolon_Colon, "Semicolon"),
  KBD_NAME_ENTRY(SYMBOL, Semicolon_Colon, "SYMBOL_Semicolon_Colon"),

  KBD_NAME_ENTRY(SYMBOL, Apostrophe_Quote, "Apostrophe"),
  KBD_NAME_ENTRY(SYMBOL, Apostrophe_Quote, "SYMBOL_Apostrophe_Quote"),

  KBD_NAME_ENTRY(SYMBOL, Comma_Less, "Comma"),
  KBD_NAME_ENTRY(SYMBOL, Comma_Less, "SYMBOL_Comma_Less"),

  KBD_NAME_ENTRY(SYMBOL, Period_Greater, "Period"),
  KBD_NAME_ENTRY(SYMBOL, Period_Greater, "SYMBOL_Period_Greater"),

  KBD_NAME_ENTRY(SYMBOL, Slash_Question, "Slash"),
  KBD_NAME_ENTRY(SYMBOL, Slash_Question, "SYMBOL_Slash_Question"),

  KBD_NAME_ENTRY(SYMBOL, Europe2, "Europe2"),

  KBD_NAME_ENTRY(FUNCTION, Escape, "Escape"),
  KBD_NAME_ENTRY(FUNCTION, Escape, "FUNCTION_Escape"),

  KBD_NAME_ENTRY(FUNCTION, Enter, "Enter"),
  KBD_NAME_ENTRY(FUNCTION, Enter, "FUNCTION_Enter"),

  KBD_NAME_ENTRY(FUNCTION, Space, "Space"),
  KBD_NAME_ENTRY(FUNCTION, Space, "FUNCTION_Space"),

  KBD_NAME_ENTRY(FUNCTION, Tab, "Tab"),
  KBD_NAME_ENTRY(FUNCTION, Tab, "FUNCTION_Tab"),

  KBD_NAME_ENTRY(FUNCTION, DeleteBackward, "DeleteBackward"),
  KBD_NAME_ENTRY(FUNCTION, DeleteBackward, "FUNCTION_DeleteBackward"),

  KBD_NAME_ENTRY(FUNCTION, F1, "F1"),
  KBD_NAME_ENTRY(FUNCTION, F1, "FUNCTION_F1"),

  KBD_NAME_ENTRY(FUNCTION, F2, "F2"),
  KBD_NAME_ENTRY(FUNCTION, F2, "FUNCTION_F2"),

  KBD_NAME_ENTRY(FUNCTION, F3, "F3"),
  KBD_NAME_ENTRY(FUNCTION, F3, "FUNCTION_F3"),

  KBD_NAME_ENTRY(FUNCTION, F4, "F4"),
  KBD_NAME_ENTRY(FUNCTION, F4, "FUNCTION_F4"),

  KBD_NAME_ENTRY(FUNCTION, F5, "F5"),
  KBD_NAME_ENTRY(FUNCTION, F5, "FUNCTION_F5"),

  KBD_NAME_ENTRY(FUNCTION, F6, "F6"),
  KBD_NAME_ENTRY(FUNCTION, F6, "FUNCTION_F6"),

  KBD_NAME_ENTRY(FUNCTION, F7, "F7"),
  KBD_NAME_ENTRY(FUNCTION, F7, "FUNCTION_F7"),

  KBD_NAME_ENTRY(FUNCTION, F8, "F8"),
  KBD_NAME_ENTRY(FUNCTION, F8, "FUNCTION_F8"),

  KBD_NAME_ENTRY(FUNCTION, F9, "F9"),
  KBD_NAME_ENTRY(FUNCTION, F9, "FUNCTION_F9"),

  KBD_NAME_ENTRY(FUNCTION, F10, "F10"),
  KBD_NAME_ENTRY(FUNCTION, F10, "FUNCTION_F10"),

  KBD_NAME_ENTRY(FUNCTION, F11, "F11"),
  KBD_NAME_ENTRY(FUNCTION, F11, "FUNCTION_F11"),

  KBD_NAME_ENTRY(FUNCTION, F12, "F12"),
  KBD_NAME_ENTRY(FUNCTION, F12, "FUNCTION_F12"),

  KBD_NAME_ENTRY(FUNCTION, F13, "F13"),
  KBD_NAME_ENTRY(FUNCTION, F13, "FUNCTION_F13"),

  KBD_NAME_ENTRY(FUNCTION, F14, "F14"),
  KBD_NAME_ENTRY(FUNCTION, F14, "FUNCTION_F14"),

  KBD_NAME_ENTRY(FUNCTION, F15, "F15"),
  KBD_NAME_ENTRY(FUNCTION, F15, "FUNCTION_F15"),

  KBD_NAME_ENTRY(FUNCTION, F16, "F16"),
  KBD_NAME_ENTRY(FUNCTION, F16, "FUNCTION_F16"),

  KBD_NAME_ENTRY(FUNCTION, F17, "F17"),
  KBD_NAME_ENTRY(FUNCTION, F17, "FUNCTION_F17"),

  KBD_NAME_ENTRY(FUNCTION, F18, "F18"),
  KBD_NAME_ENTRY(FUNCTION, F18, "FUNCTION_F18"),

  KBD_NAME_ENTRY(FUNCTION, F19, "F19"),
  KBD_NAME_ENTRY(FUNCTION, F19, "FUNCTION_F19"),

  KBD_NAME_ENTRY(FUNCTION, F20, "F20"),
  KBD_NAME_ENTRY(FUNCTION, F20, "FUNCTION_F20"),

  KBD_NAME_ENTRY(FUNCTION, F21, "F21"),
  KBD_NAME_ENTRY(FUNCTION, F21, "FUNCTION_F21"),

  KBD_NAME_ENTRY(FUNCTION, F22, "F22"),
  KBD_NAME_ENTRY(FUNCTION, F22, "FUNCTION_F22"),

  KBD_NAME_ENTRY(FUNCTION, F23, "F23"),
  KBD_NAME_ENTRY(FUNCTION, F23, "FUNCTION_F23"),

  KBD_NAME_ENTRY(FUNCTION, F24, "F24"),
  KBD_NAME_ENTRY(FUNCTION, F24, "FUNCTION_F24"),

  KBD_NAME_ENTRY(FUNCTION, Insert, "Insert"),
  KBD_NAME_ENTRY(FUNCTION, Insert, "FUNCTION_Insert"),

  KBD_NAME_ENTRY(FUNCTION, DeleteForward, "DeleteForward"),
  KBD_NAME_ENTRY(FUNCTION, DeleteForward, "FUNCTION_DeleteForward"),

  KBD_NAME_ENTRY(FUNCTION, Home, "Home"),
  KBD_NAME_ENTRY(FUNCTION, Home, "FUNCTION_Home"),

  KBD_NAME_ENTRY(FUNCTION, End, "End"),
  KBD_NAME_ENTRY(FUNCTION, End, "FUNCTION_End"),

  KBD_NAME_ENTRY(FUNCTION, PageUp, "PageUp"),
  KBD_NAME_ENTRY(FUNCTION, PageUp, "FUNCTION_PageUp"),

  KBD_NAME_ENTRY(FUNCTION, PageDown, "PageDown"),
  KBD_NAME_ENTRY(FUNCTION, PageDown, "FUNCTION_PageDown"),

  KBD_NAME_ENTRY(FUNCTION, ArrowUp, "ArrowUp"),
  KBD_NAME_ENTRY(FUNCTION, ArrowUp, "FUNCTION_ArrowUp"),

  KBD_NAME_ENTRY(FUNCTION, ArrowDown, "ArrowDown"),
  KBD_NAME_ENTRY(FUNCTION, ArrowDown, "FUNCTION_ArrowDown"),

  KBD_NAME_ENTRY(FUNCTION, ArrowLeft, "ArrowLeft"),
  KBD_NAME_ENTRY(FUNCTION, ArrowLeft, "FUNCTION_ArrowLeft"),

  KBD_NAME_ENTRY(FUNCTION, ArrowRight, "ArrowRight"),
  KBD_NAME_ENTRY(FUNCTION, ArrowRight, "FUNCTION_ArrowRight"),

  KBD_NAME_ENTRY(FUNCTION, PrintScreen, "PrintScreen"),
  KBD_NAME_ENTRY(FUNCTION, PrintScreen, "FUNCTION_PrintScreen"),

  KBD_NAME_ENTRY(FUNCTION, SystemRequest, "SystemRequest"),
  KBD_NAME_ENTRY(FUNCTION, SystemRequest, "FUNCTION_SystemRequest"),

  KBD_NAME_ENTRY(FUNCTION, Pause, "Pause"),
  KBD_NAME_ENTRY(FUNCTION, Pause, "FUNCTION_Pause"),

  KBD_NAME_ENTRY(FUNCTION, ShiftLeft, "ShiftLeft"),
  KBD_NAME_ENTRY(FUNCTION, ShiftLeft, "FUNCTION_ShiftLeft"),

  KBD_NAME_ENTRY(FUNCTION, ShiftRight, "ShiftRight"),
  KBD_NAME_ENTRY(FUNCTION, ShiftRight, "FUNCTION_ShiftRight"),

  KBD_NAME_ENTRY(FUNCTION, ControlLeft, "ControlLeft"),
  KBD_NAME_ENTRY(FUNCTION, ControlLeft, "FUNCTION_ControlLeft"),

  KBD_NAME_ENTRY(FUNCTION, ControlRight, "ControlRight"),
  KBD_NAME_ENTRY(FUNCTION, ControlRight, "FUNCTION_ControlRight"),

  KBD_NAME_ENTRY(FUNCTION, AltLeft, "AltLeft"),
  KBD_NAME_ENTRY(FUNCTION, AltLeft, "FUNCTION_AltLeft"),

  KBD_NAME_ENTRY(FUNCTION, AltRight, "AltRight"),
  KBD_NAME_ENTRY(FUNCTION, AltRight, "FUNCTION_AltRight"),

  KBD_NAME_ENTRY(FUNCTION, GuiLeft, "GuiLeft"),
  KBD_NAME_ENTRY(FUNCTION, GuiLeft, "FUNCTION_GuiLeft"),

  KBD_NAME_ENTRY(FUNCTION, GuiRight, "GuiRight"),
  KBD_NAME_ENTRY(FUNCTION, GuiRight, "FUNCTION_GuiRight"),

  KBD_NAME_ENTRY(FUNCTION, Application, "Application"),
  KBD_NAME_ENTRY(FUNCTION, Application, "FUNCTION_Application"),

  KBD_NAME_ENTRY(FUNCTION, Help, "FUNCTION_Help"),

  KBD_NAME_ENTRY(FUNCTION, Stop, "FUNCTION_Stop"),

  KBD_NAME_ENTRY(FUNCTION, Props, "FUNCTION_Props"),

  KBD_NAME_ENTRY(FUNCTION, Front, "FUNCTION_Front"),

  KBD_NAME_ENTRY(FUNCTION, Open, "FUNCTION_Open"),

  KBD_NAME_ENTRY(FUNCTION, Find, "FUNCTION_Find"),

  KBD_NAME_ENTRY(FUNCTION, Again, "FUNCTION_Again"),

  KBD_NAME_ENTRY(FUNCTION, Undo, "FUNCTION_Undo"),

  KBD_NAME_ENTRY(FUNCTION, Copy, "FUNCTION_Copy"),

  KBD_NAME_ENTRY(FUNCTION, Paste, "FUNCTION_Paste"),

  KBD_NAME_ENTRY(FUNCTION, Cut, "FUNCTION_Cut"),

  KBD_NAME_ENTRY(FUNCTION, Power, "FUNCTION_Power"),

  KBD_NAME_ENTRY(FUNCTION, Sleep, "FUNCTION_Sleep"),

  KBD_NAME_ENTRY(FUNCTION, Wakeup, "FUNCTION_Wakeup"),

  KBD_NAME_ENTRY(FUNCTION, Menu, "FUNCTION_Menu"),

  KBD_NAME_ENTRY(FUNCTION, Select, "Select"),
  KBD_NAME_ENTRY(FUNCTION, Select, "FUNCTION_Select"),

  KBD_NAME_ENTRY(FUNCTION, Cancel, "FUNCTION_Cancel"),

  KBD_NAME_ENTRY(FUNCTION, Clear, "FUNCTION_Clear"),

  KBD_NAME_ENTRY(FUNCTION, Prior, "FUNCTION_Prior"),

  KBD_NAME_ENTRY(FUNCTION, Return, "FUNCTION_Return"),

  KBD_NAME_ENTRY(FUNCTION, Separator, "FUNCTION_Separator"),

  KBD_NAME_ENTRY(FUNCTION, Out, "FUNCTION_Out"),

  KBD_NAME_ENTRY(FUNCTION, Oper, "FUNCTION_Oper"),

  KBD_NAME_ENTRY(FUNCTION, Clear_Again, "FUNCTION_Clear_Again"),

  KBD_NAME_ENTRY(FUNCTION, CrSel_Props, "FUNCTION_CrSel_Props"),

  KBD_NAME_ENTRY(FUNCTION, ExSel, "FUNCTION_ExSel"),

  KBD_NAME_ENTRY(MEDIA, Mute, "MEDIA_Mute"),

  KBD_NAME_ENTRY(MEDIA, VolumeDown, "MEDIA_VolumeDown"),

  KBD_NAME_ENTRY(MEDIA, VolumeUp, "MEDIA_VolumeUp"),

  KBD_NAME_ENTRY(MEDIA, Stop, "MEDIA_Stop"),

  KBD_NAME_ENTRY(MEDIA, Play, "MEDIA_Play"),

  KBD_NAME_ENTRY(MEDIA, Record, "MEDIA_Record"),

  KBD_NAME_ENTRY(MEDIA, Pause, "MEDIA_Pause"),

  KBD_NAME_ENTRY(MEDIA, PlayPause, "MEDIA_PlayPause"),

  KBD_NAME_ENTRY(MEDIA, Previous, "MEDIA_Previous"),

  KBD_NAME_ENTRY(MEDIA, Next, "MEDIA_Next"),

  KBD_NAME_ENTRY(MEDIA, Backward, "MEDIA_Backward"),

  KBD_NAME_ENTRY(MEDIA, Forward, "MEDIA_Forward"),

  KBD_NAME_ENTRY(MEDIA, Eject, "MEDIA_Eject"),

  KBD_NAME_ENTRY(MEDIA, Close, "MEDIA_Close"),

  KBD_NAME_ENTRY(MEDIA, EjectClose, "MEDIA_EjectClose"),

  KBD_NAME_ENTRY(LOCK, Capitals, "CapsLock"),
  KBD_NAME_ENTRY(LOCK, Capitals, "LOCK_Capitals"),

  KBD_NAME_ENTRY(LOCK, Scroll, "ScrollLock"),
  KBD_NAME_ENTRY(LOCK, Scroll, "LOCK_Scroll"),

  KBD_NAME_ENTRY(LOCKING, Capitals, "LOCKING_Capitals"),

  KBD_NAME_ENTRY(LOCKING, Scroll, "LOCKING_Scroll"),

  KBD_NAME_ENTRY(LOCKING, Numbers, "LOCKING_Numbers"),

  KBD_NAME_ENTRY(KEYPAD, NumLock_Clear, "KEYPAD_NumLock_Clear"),

  KBD_NAME_ENTRY(KEYPAD, Slash, "KPSlash"),
  KBD_NAME_ENTRY(KEYPAD, Slash, "KEYPAD_Slash"),

  KBD_NAME_ENTRY(KEYPAD, Asterisk, "KPAsterisk"),
  KBD_NAME_ENTRY(KEYPAD, Asterisk, "KEYPAD_Asterisk"),

  KBD_NAME_ENTRY(KEYPAD, Minus, "KPMinus"),
  KBD_NAME_ENTRY(KEYPAD, Minus, "KEYPAD_Minus"),

  KBD_NAME_ENTRY(KEYPAD, Plus, "KPPlus"),
  KBD_NAME_ENTRY(KEYPAD, Plus, "KEYPAD_Plus"),

  KBD_NAME_ENTRY(KEYPAD, Enter, "KPEnter"),
  KBD_NAME_ENTRY(KEYPAD, Enter, "KEYPAD_Enter"),

  KBD_NAME_ENTRY(KEYPAD, One_End, "KP1"),
  KBD_NAME_ENTRY(KEYPAD, One_End, "KPEnd"),
  KBD_NAME_ENTRY(KEYPAD, One_End, "KEYPAD_One_End"),

  KBD_NAME_ENTRY(KEYPAD, Two_ArrowDown, "KP2"),
  KBD_NAME_ENTRY(KEYPAD, Two_ArrowDown, "KPArrowDown"),
  KBD_NAME_ENTRY(KEYPAD, Two_ArrowDown, "KEYPAD_Two_ArrowDown"),

  KBD_NAME_ENTRY(KEYPAD, Three_PageDown, "KP3"),
  KBD_NAME_ENTRY(KEYPAD, Three_PageDown, "KPPageDown"),
  KBD_NAME_ENTRY(KEYPAD, Three_PageDown, "KEYPAD_Three_PageDown"),

  KBD_NAME_ENTRY(KEYPAD, Four_ArrowLeft, "KP4"),
  KBD_NAME_ENTRY(KEYPAD, Four_ArrowLeft, "KPArrowLeft"),
  KBD_NAME_ENTRY(KEYPAD, Four_ArrowLeft, "KEYPAD_Four_ArrowLeft"),

  KBD_NAME_ENTRY(KEYPAD, Five, "KP5"),
  KBD_NAME_ENTRY(KEYPAD, Five, "KEYPAD_Five"),

  KBD_NAME_ENTRY(KEYPAD, Six_ArrowRight, "KP6"),
  KBD_NAME_ENTRY(KEYPAD, Six_ArrowRight, "KPArrowRight"),
  KBD_NAME_ENTRY(KEYPAD, Six_ArrowRight, "KEYPAD_Six_ArrowRight"),

  KBD_NAME_ENTRY(KEYPAD, Seven_Home, "KP7"),
  KBD_NAME_ENTRY(KEYPAD, Seven_Home, "KPHome"),
  KBD_NAME_ENTRY(KEYPAD, Seven_Home, "KEYPAD_Seven_Home"),

  KBD_NAME_ENTRY(KEYPAD, Eight_ArrowUp, "KP8"),
  KBD_NAME_ENTRY(KEYPAD, Eight_ArrowUp, "KPArrowUp"),
  KBD_NAME_ENTRY(KEYPAD, Eight_ArrowUp, "KEYPAD_Eight_ArrowUp"),

  KBD_NAME_ENTRY(KEYPAD, Nine_PageUp, "KP9"),
  KBD_NAME_ENTRY(KEYPAD, Nine_PageUp, "KPPageUp"),
  KBD_NAME_ENTRY(KEYPAD, Nine_PageUp, "KEYPAD_Nine_PageUp"),

  KBD_NAME_ENTRY(KEYPAD, Zero_Insert, "KP0"),
  KBD_NAME_ENTRY(KEYPAD, Zero_Insert, "KPInsert"),
  KBD_NAME_ENTRY(KEYPAD, Zero_Insert, "KEYPAD_Zero_Insert"),

  KBD_NAME_ENTRY(KEYPAD, Period_Delete, "KPPeriod"),
  KBD_NAME_ENTRY(KEYPAD, Period_Delete, "KPDelete"),
  KBD_NAME_ENTRY(KEYPAD, Period_Delete, "KEYPAD_Period_Delete"),

  KBD_NAME_ENTRY(KEYPAD, Equals, "KPEquals"),
  KBD_NAME_ENTRY(KEYPAD, Equals, "KEYPAD_Equals"),

  KBD_NAME_ENTRY(KEYPAD, LeftParenthesis, "KEYPAD_LeftParenthesis"),

  KBD_NAME_ENTRY(KEYPAD, RightParenthesis, "KEYPAD_RightParenthesis"),

  KBD_NAME_ENTRY(KEYPAD, LeftBrace, "KEYPAD_LeftBrace"),

  KBD_NAME_ENTRY(KEYPAD, RightBrace, "KEYPAD_RightBrace"),

  KBD_NAME_ENTRY(KEYPAD, Modulo, "KEYPAD_Modulo"),

  KBD_NAME_ENTRY(KEYPAD, BitwiseAnd, "KEYPAD_BitwiseAnd"),

  KBD_NAME_ENTRY(KEYPAD, BitwiseOr, "KEYPAD_BitwiseOr"),

  KBD_NAME_ENTRY(KEYPAD, BitwiseXor, "KEYPAD_BitwiseXor"),

  KBD_NAME_ENTRY(KEYPAD, Less, "KEYPAD_Less"),

  KBD_NAME_ENTRY(KEYPAD, Greater, "KEYPAD_Greater"),

  KBD_NAME_ENTRY(KEYPAD, BooleanAnd, "KEYPAD_BooleanAnd"),

  KBD_NAME_ENTRY(KEYPAD, BooleanOr, "KEYPAD_BooleanOr"),

  KBD_NAME_ENTRY(KEYPAD, BooleanXor, "KEYPAD_BooleanXor"),

  KBD_NAME_ENTRY(KEYPAD, BooleanNot, "KEYPAD_BooleanNot"),

  KBD_NAME_ENTRY(KEYPAD, Backspace, "KEYPAD_Backspace"),

  KBD_NAME_ENTRY(KEYPAD, Space, "KEYPAD_Space"),

  KBD_NAME_ENTRY(KEYPAD, Tab, "KEYPAD_Tab"),

  KBD_NAME_ENTRY(KEYPAD, Comma, "KEYPAD_Comma"),

  KBD_NAME_ENTRY(KEYPAD, Colon, "KEYPAD_Colon"),

  KBD_NAME_ENTRY(KEYPAD, Number, "KEYPAD_Number"),

  KBD_NAME_ENTRY(KEYPAD, At, "KEYPAD_At"),

  KBD_NAME_ENTRY(KEYPAD, A, "KEYPAD_A"),

  KBD_NAME_ENTRY(KEYPAD, B, "KEYPAD_B"),

  KBD_NAME_ENTRY(KEYPAD, C, "KEYPAD_C"),

  KBD_NAME_ENTRY(KEYPAD, D, "KEYPAD_D"),

  KBD_NAME_ENTRY(KEYPAD, E, "KEYPAD_E"),

  KBD_NAME_ENTRY(KEYPAD, F, "KEYPAD_F"),

  KBD_NAME_ENTRY(KEYPAD, 00, "KEYPAD_00"),

  KBD_NAME_ENTRY(KEYPAD, 000, "KEYPAD_000"),

  KBD_NAME_ENTRY(KEYPAD, ThousandsSeparator, "KEYPAD_ThousandsSeparator"),

  KBD_NAME_ENTRY(KEYPAD, DecimalSeparator, "KEYPAD_DecimalSeparator"),

  KBD_NAME_ENTRY(KEYPAD, CurrencyUnit, "KEYPAD_CurrencyUnit"),

  KBD_NAME_ENTRY(KEYPAD, CurrencySubunit, "KEYPAD_CurrencySubunit"),

  KBD_NAME_ENTRY(KEYPAD, Clear, "KEYPAD_Clear"),

  KBD_NAME_ENTRY(KEYPAD, ClearEntry, "KEYPAD_ClearEntry"),

  KBD_NAME_ENTRY(KEYPAD, PlusMinus, "KEYPAD_PlusMinus"),

  KBD_NAME_ENTRY(KEYPAD, MemoryClear, "KEYPAD_MemoryClear"),

  KBD_NAME_ENTRY(KEYPAD, MemoryStore, "KEYPAD_MemoryStore"),

  KBD_NAME_ENTRY(KEYPAD, MemoryRecall, "KEYPAD_MemoryRecall"),

  KBD_NAME_ENTRY(KEYPAD, MemoryAdd, "KEYPAD_MemoryAdd"),

  KBD_NAME_ENTRY(KEYPAD, MemorySubtract, "KEYPAD_MemorySubtract"),

  KBD_NAME_ENTRY(KEYPAD, MemoryMultiply, "KEYPAD_MemoryMultiply"),

  KBD_NAME_ENTRY(KEYPAD, MemoryDivide, "KEYPAD_MemoryDivide"),

  KBD_NAME_ENTRY(KEYPAD, Binary, "KEYPAD_Binary"),

  KBD_NAME_ENTRY(KEYPAD, Octal, "KEYPAD_Octal"),

  KBD_NAME_ENTRY(KEYPAD, Decimal, "KEYPAD_Decimal"),

  KBD_NAME_ENTRY(KEYPAD, Hexadecimal, "KEYPAD_Hexadecimal"),

  KBD_NAME_ENTRY(BRAILLE, Space, "Space"),
  KBD_NAME_ENTRY(BRAILLE, Space, "BRAILLE_Space"),

  KBD_NAME_ENTRY(BRAILLE, Dot1, "Dot1"),
  KBD_NAME_ENTRY(BRAILLE, Dot1, "BRAILLE_Dot1"),

  KBD_NAME_ENTRY(BRAILLE, Dot2, "Dot2"),
  KBD_NAME_ENTRY(BRAILLE, Dot2, "BRAILLE_Dot2"),

  KBD_NAME_ENTRY(BRAILLE, Dot3, "Dot3"),
  KBD_NAME_ENTRY(BRAILLE, Dot3, "BRAILLE_Dot3"),

  KBD_NAME_ENTRY(BRAILLE, Dot4, "Dot4"),
  KBD_NAME_ENTRY(BRAILLE, Dot4, "BRAILLE_Dot4"),

  KBD_NAME_ENTRY(BRAILLE, Dot5, "Dot5"),
  KBD_NAME_ENTRY(BRAILLE, Dot5, "BRAILLE_Dot5"),

  KBD_NAME_ENTRY(BRAILLE, Dot6, "Dot6"),
  KBD_NAME_ENTRY(BRAILLE, Dot6, "BRAILLE_Dot6"),

  KBD_NAME_ENTRY(BRAILLE, Dot7, "Dot7"),
  KBD_NAME_ENTRY(BRAILLE, Dot7, "BRAILLE_Dot7"),

  KBD_NAME_ENTRY(BRAILLE, Dot8, "Dot8"),
  KBD_NAME_ENTRY(BRAILLE, Dot8, "BRAILLE_Dot8"),

  KBD_NAME_ENTRY(BRAILLE, Backward, "Backward"),
  KBD_NAME_ENTRY(BRAILLE, Backward, "BRAILLE_Backward"),

  KBD_NAME_ENTRY(BRAILLE, Forward, "Forward"),
  KBD_NAME_ENTRY(BRAILLE, Forward, "BRAILLE_Forward"),

  KEY_SET_ENTRY(KBD_SET_ROUTE, "RoutingKey"),
END_KEY_NAME_TABLE

KEY_NAME_TABLES_DECLARATION(keyboard) = {
  KEY_NAME_TABLE(keyboard),
  LAST_KEY_NAME_TABLE
};
